import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Snow Leopard: The Ghost of the Mountains - New Heights Educational Group, Inc.',
    description: 'Written By - Erika S. Hanson The snow leopard is one of nature\'s most beautiful creatures. As of 2021, the snow leopard is no longer considered an endangered species. However, the population is still at risk due to illegal poaching and the encroachment of society into the cats\' habitat. So, although it has been',
    canonical: '/educational-articles/snow-leopard-the-ghost-of-the-mountains/',
  }),
  title: { absolute: 'Snow Leopard: The Ghost of the Mountains - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-12482 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/snow-leopard-the-ghost-of-the-mountains') }}
    />
  )
}
