import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'teacher support Archives - NHEG',
    description: 'teacher support Archives: NHEG EDGuide May – June 2026.',
    canonical: '/publications/tag/teacher-support/',
  }),
  title: { absolute: 'teacher support Archives - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-teacher-support tag-66 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-no-sidebar astra-4.14.0 group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('publications/tag/teacher-support') }}
    />
  )
}
