import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Be Part of the NASA’s Parker Solar Probe Mission to the Sun - New Heights Educational Group, Inc.',
    description: 'Occasionally NASA or National Aeronautics and Space Administration like to involve the world in their missions in outer space. This Year you be part of the NASA\'s Parker Solar Probe Mission to the sun by adding your name to a microchip that will be added to the probe. The last time a registration people could',
    canonical: '/community-news/parker-solar-probe-mission/',
  }),
  title: { absolute: 'Be Part of the NASA’s Parker Solar Probe Mission to the Sun - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7092 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('community-news/parker-solar-probe-mission') }}
    />
  )
}
