// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Khrista Cendana, Author at New Heights Educational Group, Inc. | Page 2 of 3',
    description:
      'Khrista Cendana, page 2 of 3: The Importance of Travel Safety – Part I, Making Writing Interesting For Students, Anime Education – What is Anime?…',
    canonical: '/author/khrista-cendana/page/2/',
  }),
  title: {
    absolute: 'Khrista Cendana, Author at New Heights Educational Group, Inc. | Page 2 of 3',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-khrista-cendana author-4 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-2"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/khrista-cendana/page/2') }}
    />
  )
}
