import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: '2022 American Business Awards® Stevie Award Winner - New Heights Educational Group, Inc.',
    description: 'New Heights Educational Group (NHEG) was named the winner of a Gold Stevie® Award in the Education Hero of the Year category in The 20th Annual American Business Awards® today. More than 3,700 nominations from organizations of all sizes and in virtually every industry were submitted this year for consideration in a wide range of',
    canonical: '/nheg-news/2022-american-business-awards-stevie-award-winner/',
  }),
  title: { absolute: '2022 American Business Awards® Stevie Award Winner - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-12663 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/2022-american-business-awards-stevie-award-winner') }}
    />
  )
}
