import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Shannon Williamson | NHEG Radio Show | NHEG',
    description:
      "My name is Shannon, and I received my bachelor's in psychology from Christopher Newport University in Virginia and my certificate in child development from Northern Virginia Community College.",
    canonical: '/radio/shannon-williamson/',
  }),
  title: { absolute: 'Shannon Williamson | NHEG Radio Show | NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-256 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/shannon-williamson') }}
    />
  )
}
