import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'The Globee Award Winner - New Heights Educational Group, Inc.',
    description: 'The New Heights Educational Group announced today that The Globee® Awards, organizers of world’s premier business awards programs and business ranking lists, has named NHEG Business Development Outstanding Performance of the Year. GOLD GLOBEE® WINNER New Heights Educational Group | Defiance, OH USA Customer Service & Support Team of the Year | During COVID-19 BRONZE',
    canonical: '/nheg-news/the-globee-award-winner/',
  }),
  title: { absolute: 'The Globee Award Winner - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-9868 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/the-globee-award-winner') }}
    />
  )
}
