import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Classic Learning Test Continual Support - New Heights Educational Group, Inc.',
    description: 'Dear students and families, We are thrilled to announce our continued support of the Classic Learning Test. We continue our testing for students and their families who want an alternative to the ACT and SAT tests. New Heights Educational Group (NHEG) will administer the Classic Learning Test (CLT) on the following Saturdays of this academic',
    canonical: '/nheg-news/classic-learning-test-continual-support/',
  }),
  title: { absolute: 'Classic Learning Test Continual Support - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8655 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/classic-learning-test-continual-support') }}
    />
  )
}
