import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Autism Spectrum Disorder - New Heights Educational Group, Inc.',
    description:
      'Autism Spectrum Disorder is a continuum of symptoms and behaviors related to a set of disorders with similar characteristics that vary from person to person. Some individuals have mild symptoms, while others may experience more severe symptoms. Populations more susceptible to developing the disorder include male children, children whose siblings have the syndrome, and people',
    canonical: '/nheg-news/autism-spectrum-disorder/',
  }),
  title: { absolute: 'Autism Spectrum Disorder - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1436 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/autism-spectrum-disorder') }}
    />
  )
}
