import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Volunteer Opportunities - New Heights Educational Group, Inc.',
    description: '#',
    canonical: '/volunteer-with-nheg/nheg-volunteer-opportunities/',
  }),
  title: { absolute: 'NHEG Volunteer Opportunities - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-9816 page-child parent-pageid-576 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('volunteer-with-nheg/nheg-volunteer-opportunities'),
      }}
    />
  )
}
