// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Michael Anderson, Author at New Heights Educational Group, Inc. | Page 6 of 11',
    description:
      'Michael Anderson, page 6 of 11: New Heights Show on Education Custom Pin Buttons, NHEG Custom Pin Buttons, NHEG Metal Pin, NHEG AAG Metal Pin, New…',
    canonical: '/author/m-anderson/page/6/',
  }),
  title: {
    absolute: 'Michael Anderson, Author at New Heights Educational Group, Inc. | Page 6 of 11',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-m-anderson author-17 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-6"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/m-anderson/page/6') }}
    />
  )
}
