import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Volunteer Form - New Heights Educational Group, Inc.',
    description:
      'Before you can begin volunteering with New Heights Educational Group you must fill out our NHEG Volunteer Form.',
    canonical: '/volunteer-with-nheg/volunteer-form/',
  }),
  title: { absolute: 'Volunteer Form - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-5601 page-child parent-pageid-576 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('volunteer-with-nheg/volunteer-form') }}
    />
  )
}
