import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Pamela Clark – Host of New Heights Show on Education - NHEG Radio Show',
    description:
      'Mrs. Pamela Clark is the founder and executive director of New Heights Educational Group, a nonprofit located in northwest Ohio, and the New Heights Show on Education.',
    canonical: '/radio/pamela-clark/',
  }),
  title: { absolute: 'Pamela Clark – Host of New Heights Show on Education - NHEG Radio Show' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-12694 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/pamela-clark') }}
    />
  )
}
