import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Sheila Wright is now a NHEG Teacher - New Heights Educational Group, Inc.',
    description:
      'The New Heights Educational Group, (NHEG) is announcing a new teacher, Sheila Wright who will be joining the team of this award winning organization. Sheila has been a committed volunteer at NHEG since July of 2015 as a proofreader and was recently promoted to Assistant Virtual Developer Of Proofreader/Editing of Website. She will be teaching',
    canonical: '/nheg-news/welcome-sheila-wright/',
  }),
  title: { absolute: 'Sheila Wright is now a NHEG Teacher - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-6352 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/welcome-sheila-wright') }}
    />
  )
}
