import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Science Resources - NHEG Online Learning Annex',
    description: 'Here is a list of science resources for you science teachers ready to wow your students are ready to learn all sorts of science fun in the classroom.',
    canonical: '/school/teachers/classroom-resources/science-resources/',
  }),
  title: { absolute: 'Science Resources - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-683 page-child parent-pageid-680 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/teachers/classroom-resources/science-resources') }}
    />
  )
}
