import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: '2019 Golden Bridge Awards - New Heights Educational Group, Inc.',
    description: 'New Heights Educational Group (NHEG) has earned the prestigious Gold status (x2) and one Bronze status in the 2019 Golden Bridge Awards®. The coveted annual Golden Bridge Awards® program encompasses the world’s best in organizational performance, innovations, products and services, executives and management teams, women in business and the professions, innovations, best deployments, product management,',
    canonical: '/nheg-news/2019-golden-bridge-awards/',
  }),
  title: { absolute: '2019 Golden Bridge Awards - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8533 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/2019-golden-bridge-awards') }}
    />
  )
}
