// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG News - New Heights Educational Group, Inc. - Page 3',
    description:
      'Our NHEG News archive consist of articles relating to various updates to our organization as well as promoting any upcoming events that are part of in Ohio. - Page 3',
    canonical: '/category/nheg-news/page/3/',
  }),
  title: { absolute: 'NHEG News - New Heights Educational Group, Inc. - Page 3' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-nheg-news category-1 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive paged paged-3"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/nheg-news/page/3') }}
    />
  )
}
