import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Teaching Harry Potter In School - New Heights Educational Group, Inc.',
    description:
      'Why do you want to teach Harry Potter in your classroom? Is it because the series is popular among kids and adults? Are you a fan of Harry Potter and…',
    canonical: '/educational-articles/teaching-harry-potter-in-school/',
  }),
  title: { absolute: 'Teaching Harry Potter In School - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7991 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('educational-articles/teaching-harry-potter-in-school'),
      }}
    />
  )
}
