import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'Heartfelt Thanks, Special Offer, and Exciting News! 🌟 - New Heights Educational Group, Inc.',
    description:
      "Dear Pamela, We trust this message finds you well and thriving. We are thankful for your unwavering support as a TTRS affiliate. Your dedication truly lights up our world, and we are incredibly grateful for the positive impact you continue to make. Now, let's add an extra spark to your efforts! 🚀 Until December 1st,",
    canonical: '/community-news/heartfelt-thanks-special-offer-and-exciting-news-f0-9f-8c-9f/',
  }),
  title: {
    absolute:
      'Heartfelt Thanks, Special Offer, and Exciting News! 🌟 - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13258 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'community-news/heartfelt-thanks-special-offer-and-exciting-news-f0-9f-8c-9f'
        ),
      }}
    />
  )
}
