import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'FEE Stories – Why College Degrees Are Losing Their Value - New Heights Educational Group, Inc.',
    description: 'The signaling function of college degrees may have been distorted by the phenomenon known as credential inflation. The concept of inflation (the depreciation of purchasing power of a specific currency) applies to other goods besides money. Inflation is related to the Law of Supply and Demand. As the supply of a commodity increases, the value decreases. Conversely, as the good becomes',
    canonical: '/educational-articles/fee-stories-why-college-degrees-are-losing-their-value/',
  }),
  title: { absolute: 'FEE Stories – Why College Degrees Are Losing Their Value - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13069 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/fee-stories-why-college-degrees-are-losing-their-value') }}
    />
  )
}
