import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Learning Disabilities / Special Needs - NHEG Online Learning Annex',
    description:
      'Learning Disabilities in children can be especially difficult for both the parents and the children, especially when it comes to school. This can be even more difficult for home school parents, so here at NHEG, we want to provide as much information as possible to help understand your children and their needs.',
    canonical: '/school/parents/learning-disabilities-special-needs/',
  }),
  title: { absolute: 'Learning Disabilities / Special Needs - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-616 page-child parent-pageid-420 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/parents/learning-disabilities-special-needs'),
      }}
    />
  )
}
