import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'What is Homeschooling? - New Heights Educational Group, Inc.',
    description:
      'Homeschooling involves parents and/or hired instructors as teachers within the home instead of enrolling children in a public or private school. It takes hard work, patience, and responsibility to home school. Reasons why parents choose to homeschool: Religion Special needs/disability School does not challenge child to his/her full potential Bullying Transportation/convenience Family travel Things to',
    canonical: '/educational-articles/homeschooling/',
  }),
  title: { absolute: 'What is Homeschooling? - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1497 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/homeschooling') }}
    />
  )
}
