import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Show on Education Duffel Bag - New Heights Educational Group, Inc.',
    description: 'SmallLength, in19.02Height, in9.49Width, in9.49Main strap length, in27.56Handle height, in10.99Handle width , in1.5Lightweight and durable, our custom-printed duffel bags are a great way to express yourself! Perfect for the gym, day-trip, or any other mobile storage need! Easy to carry with you in your hands or around your shoulders, these duffel bags are ready to go',
    canonical: '/product/show-on-education-duffel-bag/',
  }),
  title: { absolute: 'Show on Education Duffel Bag - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11947 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/show-on-education-duffel-bag') }}
    />
  )
}
