import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Allen County Fairgrounds- Free Science Class Field Trip - New Heights Educational Group, Inc.',
    description: 'Bring your class on Friday, Oct. 19, to the Allen County Fairgrounds (Ft. Wayne) for our FREE SCHOOL DAY! This event is sponsored by the Three Rivers Gem and Mineral Society. This year’s show theme is “GEODES – The Beauty Inside”. In addition to displays, classes will have the chance to see and touch many',
    canonical: '/education-news/allen-county-fairgrounds-free-science-class-field-trip/',
  }),
  title: { absolute: 'Allen County Fairgrounds- Free Science Class Field Trip - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7707 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('education-news/allen-county-fairgrounds-free-science-class-field-trip') }}
    />
  )
}
