import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Chemistry - NHEG Online Learning Annex',
    description:
      'Welcome to the NHEG Chemistry Online Course. In this course, we will help to provide you with a better understanding of Chemistry and how it is used.',
    canonical: '/school/online-courses/chemistry/',
  }),
  title: { absolute: 'Chemistry - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-8107 page-child parent-pageid-2 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/online-courses/chemistry') }}
    />
  )
}
