import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Buffie Williams - NHEG Radio Show',
    description:
      'Buffie Williams is a former Navy spouse, author and service entrepreneur. She is the owner of AWAKEN Holistic Counseling & Psychotherapy Services, LLC and consulting agency in Troy, Alabama,.',
    canonical: '/radio/buffie-williams/',
  }),
  title: { absolute: 'Buffie Williams - NHEG Radio Show' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-8545 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/buffie-williams') }}
    />
  )
}
