import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'School and Senior Pictures - NHEG Online Learning Annex',
    description:
      'For students looking to get their pictures taken, NHEG offers high quality and reasonably priced photographers for your school and senior pictures.',
    canonical: '/school/students/school-senior-pictures/',
  }),
  title: { absolute: 'School and Senior Pictures - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-1356 page-child parent-pageid-6467 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/students/school-senior-pictures'),
      }}
    />
  )
}
