import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Radio Has Hit 100,000 Listeners - New Heights Educational Group, Inc.',
    description:
      'Last week we have received some great news about our NHEG Radio programs. We have hit the 100,000 mark with over 103,480 listeners. So not only do we want to thank our radio show hosts for putting on great shows but to every single listen who have enjoy the shows that we have produced. If',
    canonical: '/nheg-news/nheg-radio-has-hit-100000-listeners/',
  }),
  title: { absolute: 'NHEG Radio Has Hit 100,000 Listeners - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7156 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('nheg-news/nheg-radio-has-hit-100000-listeners'),
      }}
    />
  )
}
