import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG’s Renewed Partnership with izzit - New Heights Educational Group, Inc.',
    description:
      'New Heights Educational Group (NHEG) announces expansion of its 12+ year partnership with izzit.org a educational nonprofit for both students and teachers. Who is izzit.org? izzit.org believes that education can enhance the power of individuals to solve problems for themselves, their families, communities, and society at large. To solve problems, people need knowledge and skills:',
    canonical: '/nheg-news/nhegs-renewed-partnership-with-izzit/',
  }),
  title: {
    absolute: 'NHEG’s Renewed Partnership with izzit - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8935 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('nheg-news/nhegs-renewed-partnership-with-izzit'),
      }}
    />
  )
}
