import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: '2026 NHEG EDGuide Archives - NHEG',
    description: 'NHEG PUBLICATIONS This form has moved to email. We read every message. Info@NewHeightsEducation.org Sign up Sign up NHEG PUBLICATIONS Sign up Sign up 2026…',
    canonical: '/publications/category/nheg-edguide/2026-nheg-edguide/',
  }),
  title: { absolute: '2026 NHEG EDGuide Archives - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-2026-nheg-edguide category-55 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-no-sidebar astra-4.13.12 group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('publications/category/nheg-edguide/2026-nheg-edguide') }}
    />
  )
}
