import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Bullock Texas State History Museum - New Heights Educational Group, Inc.',
    description: 'The Bullock Texas State History Museum in Austin, Texas, is the state\'s official history museum and is named for the state\'s 38th Lieutenant Governor, Bob Bullock, who championed the preservation and exhibition of Texas history. Opened in 2001. the museum honors Bullock\'s vision with three floors of gallery space featuring original artifacts, a dynamic schedule oftemporary exhibitions , two theaters, and a robust film',
    canonical: '/education-news/bullock-texas-state-history-museum/',
  }),
  title: { absolute: 'Bullock Texas State History Museum - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8241 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('education-news/bullock-texas-state-history-museum') }}
    />
  )
}
