import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Reading Resources - NHEG Online Learning Annex',
    description: 'This is a list of reading resources to help you teach your students to become more effective in reading, critical thinking and writing.',
    canonical: '/school/teachers/classroom-resources/reading-resources/',
  }),
  title: { absolute: 'Reading Resources - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-815 page-child parent-pageid-680 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/teachers/classroom-resources/reading-resources') }}
    />
  )
}
