import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Managing Stress During COVID-19 - New Heights Educational Group, Inc.',
    description: 'Among many global health, economic, and societal disruptions, the COVID-19 Coronavirus outbreak has forced millions to physically isolate as this is not just a city’s, state’s or a country’s problem. It has become a WORLD PANDEMIC. Combine this with the extensive news coverage on the pandemic and an unknown future, it\'s no wonder that anxiety',
    canonical: '/student-corner/managing-stress-during-covid-19/',
  }),
  title: { absolute: 'Managing Stress During COVID-19 - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-9085 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('student-corner/managing-stress-during-covid-19') }}
    />
  )
}
