import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Photo Contest 2017 - New Heights Educational Group, Inc.',
    description:
      'Alright amateur photographers, here is your chance to put your images to the test in the NHEG Photo Contest for your chance to win 2 Disney Hopper Cards. If you are 7 to 14 years old share a photo of something that INSPIRES you, or something you LOVE! Enter your photos by December 10th in order',
    canonical: '/nheg-news/nheg-photo-contest/',
  }),
  title: { absolute: 'NHEG Photo Contest 2017 - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-6714 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-photo-contest') }}
    />
  )
}
