import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Enrichment Day - New Heights Educational Group, Inc.',
    description: 'NHEG Enrichment Day is a special day for both eager students and their parents in which we augment the participants\' interactions in the classroom. For example, students have enjoyed History classes where the classes came to life and they could speak to individuals that made a difference in the world.',
    canonical: '/events/nheg-enrichment-day/',
  }),
  title: { absolute: 'NHEG Enrichment Day - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-873 page-child parent-pageid-423 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('events/nheg-enrichment-day') }}
    />
  )
}
