import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Course Announcements - New Heights Educational Group, Inc.',
    description:
      '0 Cart This form has moved to email. We read every message. Info@NewHeightsEducation.org Course Announcements Home » Course Announcements 0 By Sarika Gauba…',
    canonical: '/category/course-announcements/',
  }),
  title: { absolute: 'Course Announcements - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-course-announcements category-12 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/course-announcements') }}
    />
  )
}
