import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Latchkey Child - New Heights Educational Group, Inc.',
    description:
      'What is the definition of a latchkey child? A latchkey is a child who returns from school to an empty home because their parent or parents are away at work, or a child who is often left at home with little parental supervision. I never stayed home alone when I was young. I began to',
    canonical: '/educational-articles/latchkey-child/',
  }),
  title: { absolute: 'Latchkey Child - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-3374 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/latchkey-child') }}
    />
  )
}
