import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Contact Us - NHEG Online Learning Annex',
    description:
      'Contact the New Heights Educational Group Learning Annex with your questions, comments, or other information about our classes or tutoring services. We…',
    canonical: '/school/contact-us/',
  }),
  title: { absolute: 'Contact Us - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-216 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/contact-us') }}
    />
  )
}
