import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Hello world! - NHEG Radio Show',
    description:
      'Welcome to WordPress. This is your first post. Edit or delete it, then start writing!',
    canonical: '/radio/uncategorized/hello-world/',
  }),
  title: { absolute: 'Hello world! - NHEG Radio Show' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1 single-format-standard wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/uncategorized/hello-world') }}
    />
  )
}
