import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'Important Things I Learned from my Learning Disability - New Heights Educational Group, Inc.',
    description:
      'Comparatively little was known about learning disabilities when I began school in the 1960s. What educators were agreeing on then was that, if a teacher understood their subject well, all their students should be able to learn that subject.',
    canonical: '/educational-articles/important-things-i-learned-from-my-learning-disability/',
  }),
  title: {
    absolute:
      'Important Things I Learned from my Learning Disability - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7670 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'educational-articles/important-things-i-learned-from-my-learning-disability'
        ),
      }}
    />
  )
}
