import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'NHEG Recognition From Ohio & Eagle River Nomination - New Heights Educational Group, Inc.',
    description:
      'Pamela Clark, Executive Director of the New Heights Educational Group (NHEG), has been recognized in not one but three ways recently. A couple of weeks ago, we had posted that Pamela was awarded the 2018 Golden Bridge Making Impact, Executive of the Year (Silver) and thanks to that award the House of Representatives for the state',
    canonical: '/nheg-news/nheg-recognition-from-ohio-eagle-river-nomination/',
  }),
  title: {
    absolute:
      'NHEG Recognition From Ohio & Eagle River Nomination - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7768 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('nheg-news/nheg-recognition-from-ohio-eagle-river-nomination'),
      }}
    />
  )
}
