import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Welcome to NHEG Radio',
    description:
      'Welcome to the New Heights Show on Education, an internet radio program and podcast in which the hosts cover various topics of education for Home, Charter and Public-School families in Ohio and beyond.',
    canonical: '/radio/',
  }),
  title: { absolute: 'Welcome to NHEG Radio' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone home wp-singular page-template-default page page-id-38 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio') }}
    />
  )
}
