import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Erika Hanson - NHEG Radio Show',
    description:
      'Erika graduated in 1999 with a B.A. in English and Psychology. In the years that followed, she was employed as a medical secretary in a variety of disciplines, including Psychiatry, Family Practice and Urology',
    canonical: '/radio/erika-hanson/',
  }),
  title: { absolute: 'Erika Hanson - NHEG Radio Show' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-8063 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/erika-hanson') }}
    />
  )
}
