import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Teacher Resources - NHEG Online Learning Annex',
    description:
      'This is a list of teacher resources provides material in the form of articles, videos and audio recordings to help you become a more effective teacher.',
    canonical: '/school/teachers/teacher-resources/',
  }),
  title: { absolute: 'Teacher Resources - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-6463 page-parent page-child parent-pageid-260 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/teachers/teacher-resources') }}
    />
  )
}
