import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Teacher and Professional Organizations - NHEG Online Learning Annex',
    description: 'This is a list of teacher and professional organizations in the state of Ohio for teachers to attend events, receive training and more. Of course, if you\'re a school administrator or working somewhere else in the educational system, these organizations will help you become a more effective leader.',
    canonical: '/school/teachers/teacher-resources/teacher-and-professional-organizations/',
  }),
  title: { absolute: 'Teacher and Professional Organizations - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-6462 page-child parent-pageid-6463 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/teachers/teacher-resources/teacher-and-professional-organizations') }}
    />
  )
}
