import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Pamela Clark',
    description:
      'Pamela Clark: Platinum Seal of Transparency 2024, Endangered: The Mexican Grey Wolf, Nelson Medela, Malcolm X, Harriet Tubman, Snow Leopard: The Ghost of…',
    canonical: '/author/pamela-clark/',
  }),
  title: { absolute: 'Pamela Clark' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-pamela-clark author-18 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/pamela-clark') }}
    />
  )
}
