import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Donation Confirmation - NHEG Online Learning Annex',
    description:
      'Login This form has moved to email. We read every message. Info@NewHeightsEducation.org Create Account This form has moved to email. We read every message…',
    canonical: '/school/donation-confirmation/',
  }),
  title: { absolute: 'Donation Confirmation - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-6871 wp-theme-jupiter give-success give-page wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/donation-confirmation') }}
    />
  )
}
