import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Donation Failed - NHEG Online Learning Annex',
    description: 'We\'re sorry, your donation failed to process. Please try again or contact site support.',
    canonical: '/school/donation-failed/',
  }),
  title: { absolute: 'Donation Failed - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-6872 wp-theme-jupiter give-failed-transaction give-page wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/donation-failed') }}
    />
  )
}
