/**
 * @jest-environment node
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

// src/lib/clone-content.ts and the layout are regenerated by workflow 706. A
// re-run that drops the production marker, the postbuild inliner or the
// reload puts the export back over the 1 GB Pages limit (#43).
describe('clone content in a production build', () => {
  const env = process.env.NODE_ENV
  afterEach(() => {
    ;(process.env as Record<string, string | undefined>).NODE_ENV = env
  })

  const load = (name: string) => {
    let out = ''
    jest.isolateModules(() => {
      out = require('@/lib/clone-content').loadCloneContent(name)
    })
    return out
  }

  it('renders a marker instead of the fragment', () => {
    ;(process.env as Record<string, string | undefined>).NODE_ENV = 'production'
    expect(load('index')).toMatch(/^<!--ffc-clone:index [^\s-]* [^\s-]*-->$/)
  })

  it('renders the fragment outside production', () => {
    expect(load('index').length).toBeGreaterThan(10000)
  })

  it('inlines the fragments after every build, and reloads after a client-side navigation', () => {
    const pkg = JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf8'))
    // Inline first: the search index (#49) is built from the inlined pages.
    expect(pkg.scripts.postbuild).toBe('node scripts/inline-clone-content.mjs && pagefind')
    const layout = readFileSync(join(process.cwd(), 'src', 'app', 'layout.tsx'), 'utf8')
    expect(layout).toMatch(/<CloneReload \/>/)
  })
})
