import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'Golden Bridge Awards – Making Impact, Executive of the Year - New Heights Educational Group, Inc.',
    description:
      'Pamela Clark has earned the prestigious Silver status in the Golden Bridge Awards® for her Making Impact, Executive of the Year. The coveted annual Golden Bridge Awards program encompasses the world’s best in organizational performance, innovations, products and services, executives and management teams, women in business and the professions, innovations, best deployments, product management, public',
    canonical: '/nheg-news/golden-bridge-awards-making-impact-executive-of-the-year/',
  }),
  title: {
    absolute:
      'Golden Bridge Awards – Making Impact, Executive of the Year - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7719 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'nheg-news/golden-bridge-awards-making-impact-executive-of-the-year'
        ),
      }}
    />
  )
}
