import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Savneet Singh',
    description:
      'Savneet Singh: Games and Learning, Collaborative Learning in Online Environment, Bite-size Information for Teaching and Training, Online Learning Tips…',
    canonical: '/author/savneet-singh/',
  }),
  title: { absolute: 'Savneet Singh' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-savneet-singh author-16 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/savneet-singh') }}
    />
  )
}
