// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Education News - New Heights Educational Group, Inc. - Page 2',
    description: '- Page 2',
    canonical: '/category/education-news/page/2/',
  }),
  title: { absolute: 'Education News - New Heights Educational Group, Inc. - Page 2' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-education-news category-10 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive paged paged-2"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/education-news/page/2') }}
    />
  )
}
