import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Student Leadership Council - NHEG Online Learning Annex',
    description:
      "Student Leadership Council's mission is to promote literacy for children and adults by offering a range of educational support services. Such services include assisting families in the selection of schools, organization of educational activities and acquisition of materials.",
    canonical: '/school/about/nheg-groups/student-leadership-council/',
  }),
  title: { absolute: 'Student Leadership Council - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-6461 page-child parent-pageid-6458 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/about/nheg-groups/student-leadership-council'),
      }}
    />
  )
}
