import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'NHEG Win 2021 Silver Stevie Award for Women in Business - New Heights Educational Group, Inc.',
    description:
      'New Heights Educational Group has been named the winner of a Silver Stevie® Award in the category of Organization of the Year – Government or Non-Profit – More Than 10 Employees in the 18th annual Stevie Awards for Women in Business. The Stevie Awards for Women in Business honor women executives, entrepreneurs, employees, and the',
    canonical: '/nheg-news/nheg-win-2021-silver-stevie-award-for-women-in-business/',
  }),
  title: {
    absolute:
      'NHEG Win 2021 Silver Stevie Award for Women in Business - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-10087 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'nheg-news/nheg-win-2021-silver-stevie-award-for-women-in-business'
        ),
      }}
    />
  )
}
