import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'CHEO Commencement Ceremony - New Heights Educational Group, Inc.',
    description:
      'CHEO Commencement Ceremony CELEBRATING A MILESTONE...WITH YOU! When and Where May 27, 2023! Location: Mount Vernon Nazarene University Chapel 800 Martinsburg Road, Mt. Vernon, Ohio CHEO Commencement | CHEO (cheohome.org)',
    canonical: '/nheg-news/cheo-commencement-ceremony/',
  }),
  title: { absolute: 'CHEO Commencement Ceremony - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13111 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/cheo-commencement-ceremony') }}
    />
  )
}
