import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NewHeightsEducation, Author at NHEG Radio Show',
    description: 'NewHeightsEducation: Hello world.',
    canonical: '/radio/author/newheightseducation/',
  }),
  title: { absolute: 'NewHeightsEducation, Author at NHEG Radio Show' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-newheightseducation author-1 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/author/newheightseducation') }}
    />
  )
}
