import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Writing Contest - New Heights Educational Group, Inc.',
    description: 'It\'s August and that means we are a month away from starting a new school year and it also means a end of your summer NHEG writing contest. That is what kids, we are kicking off the school season with a writing contest and the title of this contest is "Summer Educational Experience". What does',
    canonical: '/nheg-news/nheg-writing-contest/',
  }),
  title: { absolute: 'NHEG Writing Contest - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-6158 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-writing-contest') }}
    />
  )
}
