import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Volunteer of the Year Single Loop Necklace - New Heights Educational Group, Inc.',
    description: 'One SizeCoin Pendant Diameter, in0.79Lotus Coin Pendant Diameter, in0.67Tile Pendant Length, in0.87Tile Pendant Width, in0.24This single loop necklace emphasizes individuality with a classic aesthetic. Made in USA. .: Sterling silver or 18K gold plated.: Multiple chain lengths.: Several charm shapes.: Nickel and lead free',
    canonical: '/product/nheg-volunteer-of-the-year-single-loop-necklace/',
  }),
  title: { absolute: 'NHEG Volunteer of the Year Single Loop Necklace - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-12190 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/nheg-volunteer-of-the-year-single-loop-necklace') }}
    />
  )
}
