import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Breaking News Archives - NHEG',
    description:
      'NHEG PUBLICATIONS This form has moved to email. We read every message. Info@NewHeightsEducation.org Sign up Sign up NHEG PUBLICATIONS Sign up Sign up…',
    canonical: '/publications/category/breaking-news/',
  }),
  title: { absolute: 'Breaking News Archives - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-breaking-news category-46 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-no-sidebar astra-4.13.12 group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('publications/category/breaking-news') }}
    />
  )
}
