import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Educational Articles - New Heights Educational Group, Inc.',
    description: 'Our educational articles archives consist of education based articles written by teachers, students and other members of the community.',
    canonical: '/category/educational-articles/',
  }),
  title: { absolute: 'Educational Articles - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-educational-articles category-3 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/educational-articles') }}
    />
  )
}
