import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Recognition Day 201 - New Heights Educational Group, Inc.',
    description: 'Unfortunately we will be moving the NHEG Recognition Day 2018 event online. New Heights Educational Group cordial invites you to NHEG Recognition Day 2018 on Saturday June 2 from 2:30 pm to 5:00 PM at the ProMedica Defiance Regional Hospital. Recognition Day is a special event in which we recognize all the hard work that has',
    canonical: '/nheg-news/nheg-recognition-day-2018/',
  }),
  title: { absolute: 'NHEG Recognition Day 201 - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7174 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-recognition-day-2018') }}
    />
  )
}
