import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Pre-Kindergarten Associate Certification - NHEG Online Learning Annex',
    description: 'Interested in working with children between the ages of three and five? Then you will need attend a school that has the Pre-Kindergarten Associate Certification. With this certificate along with Child Development Associate Certificate, these two programs will prepare for working with young children in the State of Ohio.',
    canonical: '/school/teachers/teacher-resources/pre-kindergarten-associate-certification/',
  }),
  title: { absolute: 'Pre-Kindergarten Associate Certification - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-827 page-child parent-pageid-6463 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/teachers/teacher-resources/pre-kindergarten-associate-certification') }}
    />
  )
}
