import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Homeschooling: A New Perspective of Educating - New Heights Educational Group, Inc.',
    description: 'Homeschooling is the name given to the educational process kept at home under the teaching and guidance of parents or guardians. This is a new teaching approach for parents and children and a new educational alternative to the formal learning environments. Among the reasons that motivate more parents to teach their children at home are',
    canonical: '/educational-articles/homeschooling-a-new-perspective-of-educating/',
  }),
  title: { absolute: 'Homeschooling: A New Perspective of Educating - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1387 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/homeschooling-a-new-perspective-of-educating') }}
    />
  )
}
