// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Pamela Clark',
    description:
      '0 Cart This form has moved to email. We read every message. info@newheightseducation.org Archives Author Archive for: "Pamela Clark" Home » Archives for…',
    canonical: '/author/pamela-clark/page/4/',
  }),
  title: { absolute: 'Pamela Clark' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-pamela-clark author-18 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-4"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/pamela-clark/page/4') }}
    />
  )
}
