import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Welcome Maria Lang - New Heights Educational Group, Inc.',
    description:
      'The New Heights Educational Group is happy to welcome Maria Lang to our educational team. We are excited about her affordable and high quality art classes. We know that families struggle to come up with art projects that cover a variety of topics. Art Talk’n ($19/month or $190/year) Art Talk’n will teach you to express yourself',
    canonical: '/nheg-news/welcome-maria-lang/',
  }),
  title: { absolute: 'Welcome Maria Lang - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1290 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/welcome-maria-lang') }}
    />
  )
}
