import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'SAT Test - NHEG Online Learning Annex',
    description: 'The SAT is one of two major exams that all major colleges and universities in the United States used as part of its admissions package into their school. This test is meant to show schools how prepared you are for college by measuring key skills like reading comprehension, computational ability, and clarity of expression.',
    canonical: '/school/students/college-entrance-exams/sat-admission-test/',
  }),
  title: { absolute: 'SAT Test - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-759 page-child parent-pageid-379 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/students/college-entrance-exams/sat-admission-test') }}
    />
  )
}
