import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Anime Education – What is Anime? - New Heights Educational Group, Inc.',
    description: 'What is anime? An anime is a cartoon made in Japan in which the graphics and the art are completely different from American cartoons. Just like how the Harry Potter movies are based on books, there are some anime based on manga, Japanese comic books. Manga is its own topic, so for now let’s just',
    canonical: '/educational-articles/anime-education-what-is-anime/',
  }),
  title: { absolute: 'Anime Education – What is Anime? - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7601 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/anime-education-what-is-anime') }}
    />
  )
}
