import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Welcome Enjoli Baker - New Heights Educational Group, Inc.',
    description: 'Please welcome Enjoli Baker as she is the new Assistant Director of Education Department for New Heights Educational Group. Enjoli Baker is from Savannah, Georgia. She has three fur babies and is married. She is a lover of anything that involves education. She has an MBA and an MPH degree (Masters in Public Health). She',
    canonical: '/nheg-news/welcome-enjoli-baker/',
  }),
  title: { absolute: 'Welcome Enjoli Baker - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8857 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/welcome-enjoli-baker') }}
    />
  )
}
