import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Organic T-Shirt Dress - New Heights Educational Group, Inc.',
    description:
      'XS S M L XL Width, in 16.93 17.91 18.90 19.88 20.87 Length, in 32.87 33.86 34.84 35.83 36.81 The organic cotton t-shirt dress is made of 100% ringspun cotton – a comfortable and durable fabric. All materials are grown and gathered without the use of pesticides. This short-length t-shirt dress has a scoop',
    canonical: '/product/organic-t-shirt-dress-2/',
  }),
  title: { absolute: 'Organic T-Shirt Dress - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-12215 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/organic-t-shirt-dress-2') }}
    />
  )
}
