import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Achieve Your Fitness Goal with a Personal Fitness Trainer - NHEG',
    description: 'NHEG PUBLICATIONS This form has moved to email. We read every message. Info@NewHeightsEducation.org Sign up Sign up NHEG PUBLICATIONS Sign up Sign up…',
    canonical: '/publications/achieve-your-fitness-goal-with-a-personal-fitness-trainer/',
  }),
  title: { absolute: 'Achieve Your Fitness Goal with a Personal Fitness Trainer - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-5609 single-format-standard wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-narrow-container ast-separate-container ast-no-sidebar astra-4.13.12 group-blog ast-blog-single-style-1 ast-single-post ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header ast-normal-title-enabled elementor-default elementor-kit-5709"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('publications/achieve-your-fitness-goal-with-a-personal-fitness-trainer') }}
    />
  )
}
