import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'The Importance of Travel Safety – Part I - New Heights Educational Group, Inc.',
    description: 'Are you thinking about travelling abroad to visit a new place? Exploring new locations is always fun and enjoyable no matter whether you’re by yourself or with someone else. However, having fun shouldn’t be your only concern once you reach the destination. The importance of safety should always be a concern for individuals who like',
    canonical: '/educational-articles/the-importance-of-travel-safety-part-i/',
  }),
  title: { absolute: 'The Importance of Travel Safety – Part I - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7844 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/the-importance-of-travel-safety-part-i') }}
    />
  )
}
