import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Developing the Potential in Children with Attention-Hyperactivity Disorder - New Heights Educational Group, Inc.',
    description: 'Attention-hyperactivity disorder is a neurodevelopmental disorder that has features such as inattention, hyperactivity, and/or impulsivity. For a child to be diagnosed with this disorder, the manifestation of these features in at least two different environments of the life of the child is required—for example, at home, at school, on outings with family and friends, or',
    canonical: '/nheg-news/developing-potential-children-attention-hyperactivity-disorder/',
  }),
  title: { absolute: 'Developing the Potential in Children with Attention-Hyperactivity Disorder - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1434 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/developing-potential-children-attention-hyperactivity-disorder') }}
    />
  )
}
