import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Uncategorized Archives - NHEG Radio Show',
    description: 'Uncategorized Archives: Hello world!.',
    canonical: '/radio/category/uncategorized/',
  }),
  title: { absolute: 'Uncategorized Archives - NHEG Radio Show' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-uncategorized category-1 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/category/uncategorized') }}
    />
  )
}
