import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: '2018 Exam Dates - New Heights Educational Group, Inc.',
    description: 'In continuation of our last post about the CLT exam dates, the NHEG team has collected 2018 exam dates for the following college entrance exams: ACT, GRE, LSAT, SAT, SAT II and SSAT. An important note, if you want to double check on these dates please contact your school or testing center in making sure',
    canonical: '/education-news/2018-exam-dates/',
  }),
  title: { absolute: '2018 Exam Dates - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-6870 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('education-news/2018-exam-dates') }}
    />
  )
}
