import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'The Animation Course - NHEG Online Learning Annex',
    description:
      'Our first and primary course, the animation course consists of 4 levels with the goal of giving the student the tools they need to enjoy the process of creating stories and animating them, thus producing their own short films.',
    canonical: '/school/online-courses/animation-course/',
  }),
  title: { absolute: 'The Animation Course - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-3040 page-child parent-pageid-2 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/online-courses/animation-course'),
      }}
    />
  )
}
