import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Unisex Heavy Blend™ Hooded Sweatshirt - New Heights Educational Group, Inc.',
    description:
      'SMLXL2XL3XL4XL5XLLength, in27.1727.9629.1429.9331.1131.8933.0833.86Width, in20.0822.0524.0225.992829.9331.8933.86Sleeve length from CB, in3334.023535.9937.013839.0240Crafted for comfort, this lighter weight sweatshirt is perfect for relaxing. Once put on, it will be impossible to take off..: Classic fit.: 50% Cotton; 50% Polyester (fibre content may vary for different colors).: Medium fabric (8.0 oz/yd² (271.25 g/m²)).: Sewn in label.: Runs true to size',
    canonical: '/product/nheg-unisex-heavy-blend-hooded-sweatshirt/',
  }),
  title: {
    absolute: 'NHEG Unisex Heavy Blend™ Hooded Sweatshirt - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11655 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('product/nheg-unisex-heavy-blend-hooded-sweatshirt'),
      }}
    />
  )
}
