import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Fundraising for NHEG - New Heights Educational Group, Inc.',
    description: 'Fundraising for NHEG earns money through various fundraising programs, so the more you participate, the more we earn for our student programs and services. We provide step-by-step instructions for participating in each program, especially if you have accounts with these partner websites already.',
    canonical: '/support-nheg/fundraising-for-nheg/',
  }),
  title: { absolute: 'Fundraising for NHEG - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-2127 page-child parent-pageid-1897 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('support-nheg/fundraising-for-nheg') }}
    />
  )
}
