import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Learning Chinese - NHEG Online Learning Annex',
    description:
      'The 10-week course will take place for an hour, twice a week and will be open for middle school to adult students who wish to learn to speak and write…',
    canonical: '/school/online-courses/learning-chinese/',
  }),
  title: { absolute: 'Learning Chinese - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-7786 page-child parent-pageid-2 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/online-courses/learning-chinese'),
      }}
    />
  )
}
