import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: "Pamela's Talk - New Heights Educational Group, Inc.",
    description:
      'Pamela’s Talk is a video series of Pamela Clark talking about various educational topics and what is currently happening at New Heights Educational Group.',
    canonical: '/category/pamelas-talk/',
  }),
  title: { absolute: "Pamela's Talk - New Heights Educational Group, Inc." },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-pamelas-talk category-9 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/pamelas-talk') }}
    />
  )
}
