import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Performing Arts - NHEG Online Learning Annex',
    description: 'This is a list of performing arts resources that will help introduce or expand teaching your students to act, sing, dance and more. We also have access to various performing arts locations that give away free tickets to students as well.',
    canonical: '/school/teachers/classroom-resources/performing-arts/',
  }),
  title: { absolute: 'Performing Arts - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-1349 page-child parent-pageid-680 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/teachers/classroom-resources/performing-arts') }}
    />
  )
}
