import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'New Heights Educational Group Services - New Heights Educational Group, Inc.',
    description:
      'New Heights Educational Group offers tutoring for those who want or need a boost in learning. You’ll find a list of our current classes and rates…',
    canonical: '/who-we-are/new-heights-educatioal-group-services/',
  }),
  title: {
    absolute: 'New Heights Educational Group Services - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-13633 page-child parent-pageid-3409 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('who-we-are/new-heights-educatioal-group-services'),
      }}
    />
  )
}
