import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'High School Diploma - New Heights Educational Group, Inc.',
    description:
      'A high school diploma is a diploma that a high school student would get for finishing high school. You could also get a high school diploma if you’re being taught online for homeschooling. Getting a high school diploma is not just for kids; it is for adults or the elderly too. If you dropped out',
    canonical: '/educational-articles/high-school-diploma/',
  }),
  title: { absolute: 'High School Diploma - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1501 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('educational-articles/high-school-diploma'),
      }}
    />
  )
}
