import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'SLC Unisex Hooded Zip Sweatshirt - New Heights Educational Group, Inc.',
    description:
      'There’s nothing like a soft hooded hoodie to layer for cold winters. This hooded full zip sweatshirt features a soft and qualitative 50% cotton - 50% polyester fabric that has a regular fit and assures the perfect balance of long-lasting comfort and a contemporary silhouette. It’s in a unisex style design to fit both men',
    canonical: '/product/slc-unisex-hooded-zip-sweatshirt/',
  }),
  title: { absolute: 'SLC Unisex Hooded Zip Sweatshirt - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11811 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('product/slc-unisex-hooded-zip-sweatshirt'),
      }}
    />
  )
}
