import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Charter School Families - NHEG Online Learning Annex',
    description: 'New Heights Educational Group provides services to students and parents of students who attend charter schools in the Northwestern part of Ohio. This includes the following counties; Allen, Defiance, Delphos, Hancock, Henry, Lima, Lucas, Napoleon, Putnam, Paulding, Van Wert, Wauseon, Williams and Wood.',
    canonical: '/school/parents/charter-school-families/',
  }),
  title: { absolute: 'Charter School Families - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-476 page-parent page-child parent-pageid-420 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/parents/charter-school-families') }}
    />
  )
}
