import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Press - New Heights Educational Group, Inc.',
    description:
      'The NHEG Press center contains online articles, videos and other media formats from news outlets and websites from Ohio and across the country. Select the database below and from there you can read, watch or listen to New Heights Educational Group talking about what we do.',
    canonical: '/who-we-are/nheg-press/',
  }),
  title: { absolute: 'Press - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-216 page-parent page-child parent-pageid-3409 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('who-we-are/nheg-press') }}
    />
  )
}
