import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Education News - New Heights Educational Group, Inc.',
    description:
      'Education News: Endangered: The Mexican Grey Wolf, Partnership with CollegeXpress, Pokemon TCG, Bullock Texas State History Museum, Safety For Kids…',
    canonical: '/category/education-news/',
  }),
  title: { absolute: 'Education News - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-education-news category-10 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/education-news') }}
    />
  )
}
