import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Ultra Cotton Long Sleeve Tee - New Heights Educational Group, Inc.',
    description:
      'A bit more formal than a standard-issue t-shirt, the ultra cotton long sleeve tee is a clear comfort winner. The sleeves also act as a nice frame. There are no side seams. The shoulders are tapped for improved durability. This makes for a good fitting around the shoulders and neck. The cotton used for these',
    canonical: '/product/ultra-cotton-long-sleeve-tee/',
  }),
  title: { absolute: 'Ultra Cotton Long Sleeve Tee - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11165 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/ultra-cotton-long-sleeve-tee') }}
    />
  )
}
