import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'How to increase your productivity at home - New Heights Educational Group, Inc.',
    description: 'One thing I’m sure everyone has learned through quarantine is how difficult it can be to work at home. The members of your family, snacks in your pantry, and the feeling of laziness or comfort you associate with your house are just a few of the endless distractions that negatively affect your productivity. Now that',
    canonical: '/student-corner/how-to-increase-your-productivity-at-home/',
  }),
  title: { absolute: 'How to increase your productivity at home - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-9181 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('student-corner/how-to-increase-your-productivity-at-home') }}
    />
  )
}
