import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Mousepad (all logos) - New Heights Educational Group, Inc.',
    description: '9"x7.5"Height, in0.16Length, in9.14Width, in7.64An appealing accent on one\'s desk, this high quality mousepad is designed to provide a smooth, consistent, and durable surface. With personalized design print it will be an attractive decor on every desk..: 4 mm thick Neoprene.: Non-Slip.: Full print',
    canonical: '/product/nheg-mousepad-all-logos/',
  }),
  title: { absolute: 'NHEG Mousepad (all logos) - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11915 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/nheg-mousepad-all-logos') }}
    />
  )
}
