import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'First Book Access Request - New Heights Educational Group, Inc.',
    description:
      'Do you have a student in need? New Heights Educational Group now provides thousands of FREE ebooks for students in need.',
    canonical: '/first-book-access-request/',
  }),
  title: { absolute: 'First Book Access Request - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-13324 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('first-book-access-request') }}
    />
  )
}
