import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Prom Cruise Celebration - New Heights Educational Group, Inc.',
    description:
      'It’s a “Prom Cruise Celebration” Boat Prom is June 6, 2023 Homeschool Graduates and Undergraduates get ready for Dancing On The Water Homeschool Prom Cruise! Save by purchasing March tickets! https://boatprom.ticketspice.com/2023 Dancing On The Water Prom 2023 Get Tickets for Dancing On The Water Prom 2023. Ticket sales close June 1st 2023.',
    canonical: '/nheg-news/prom-cruise-celebration/',
  }),
  title: { absolute: 'Prom Cruise Celebration - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13108 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/prom-cruise-celebration') }}
    />
  )
}
