import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'School Bag Giveaway - New Heights Educational Group, Inc.',
    description: 'Before the school year begins, NHEG runs the School Bag Give Away a event to help local children get access to all the school supplies they will need.',
    canonical: '/events/school-bag-give-away/',
  }),
  title: { absolute: 'School Bag Giveaway - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-8124 page-child parent-pageid-423 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('events/school-bag-give-away') }}
    />
  )
}
