import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Memories of a childhood rich in stimulus and its importance for brain development - New Heights Educational Group, Inc.',
    description: 'My education was rich in stimulus. From an early age, I was inserted into the great world of letters. I remember watching my father carefully consulting the dictionary while reading the newspaper. He looked at me and read the new word he had just learned in the dictionary. Even without understanding the meaning of every',
    canonical: '/educational-articles/memories-of-a-childhood-rich-in-stimulus-and-its-importance-for-brain-development/',
  }),
  title: { absolute: 'Memories of a childhood rich in stimulus and its importance for brain development - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8402 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/memories-of-a-childhood-rich-in-stimulus-and-its-importance-for-brain-development') }}
    />
  )
}
