import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Scholarship Search - NHEG Online Learning Annex',
    description: 'NHEG has spent many years collecting and collaborating with others to compile a large list of scholarships, colleges and other resources for students. All this scholarship and grant information is stored in a database called "Donate Clearly" that we used for students looking to pay for college.',
    canonical: '/school/students/scholarship-opportunities/scholarship-search/',
  }),
  title: { absolute: 'Scholarship Search - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-1560 page-child parent-pageid-373 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/students/scholarship-opportunities/scholarship-search') }}
    />
  )
}
