import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: '2021 NHEG EdGuide Archives - NHEG',
    description:
      '2021 NHEG EdGuide Archives: NHEG EDGuide November-December 2021, NHEG EDGuide September-October 2021, NHEG EDGuide July-August 2021, NHEG EDGuide…',
    canonical: '/publications/category/nheg-edguide/2021-nheg-edguide/',
  }),
  title: { absolute: '2021 NHEG EdGuide Archives - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-2021-nheg-edguide category-33 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-no-sidebar astra-4.14.0 group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('publications/category/nheg-edguide/2021-nheg-edguide'),
      }}
    />
  )
}
