import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Financial Literacy - NHEG Online Learning Annex',
    description:
      'Taught by Heather Ruggiero , our Financial Literacy course is a self-directed class that helps you build a better understanding of your finances. This…',
    canonical: '/school/online-courses/financial-literacy/',
  }),
  title: { absolute: 'Financial Literacy - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-337 page-child parent-pageid-2 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/online-courses/financial-literacy'),
      }}
    />
  )
}
