import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'In The wings Performance - New Heights Educational Group, Inc.',
    description: 'In The wings Performance Thursday, Feb. 8th 7:30 PM Arts United Center Please call the Box Office at (260) 424-5220 with your coupon code to reserve your free tickets to this event! This production is rated PG-13. Contact Danielle Andersen at dandersen@fwcivic.org with any questions.',
    canonical: '/nheg-news/in-the-wings-performance/',
  }),
  title: { absolute: 'In The wings Performance - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13281 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/in-the-wings-performance') }}
    />
  )
}
