import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Transitioning To A Productive Schedule After Summer - New Heights Educational Group, Inc.',
    description: 'Stuck in a lazy summer schedule? Here are the answers to your 3 biggest problems. As the new school year begins, it can be difficult to get out of your summer vacation mindset. Staying up late, sleeping in, and doing no work have been regular activities for two months, so it’s hard to suddenly change',
    canonical: '/student-corner/transitioning-to-a-productive-schedule-after-summer/',
  }),
  title: { absolute: 'Transitioning To A Productive Schedule After Summer - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-9125 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('student-corner/transitioning-to-a-productive-schedule-after-summer') }}
    />
  )
}
