// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Michael Anderson, Author at New Heights Educational Group, Inc. | Page 8 of 11',
    description:
      'Michael Anderson, page 8 of 11: NHEG Latte mug, NHEG Mug 11oz, New Heights Show on Education Drawstring Bag, SLC Drawstring Bag, NHEG Unisex Heavy Cotton…',
    canonical: '/author/m-anderson/page/8/',
  }),
  title: {
    absolute: 'Michael Anderson, Author at New Heights Educational Group, Inc. | Page 8 of 11',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-m-anderson author-17 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-8"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/m-anderson/page/8') }}
    />
  )
}
