import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Promotions - New Heights Educational Group, Inc.',
    description: 'New Heights Educational Group would like to congratulate two of our volunteers with promotions within our organization, Michael Anderson and Marina Klimi. Marina Klimi has been a graphic designer with us since 2013. She has helped us with many projects, including our book and magazine covers, radio show banners, birthday and seasonal cards and so',
    canonical: '/nheg-news/nheg-promotions/',
  }),
  title: { absolute: 'NHEG Promotions - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-5065 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-promotions') }}
    />
  )
}
