import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'FEE Stories – I Grew Up in a Communist System. Here’s What Americans Don’t Understand About Freedom - New Heights Educational Group, Inc.',
    description:
      'Only in a free-market system can we truly achieve individual liberty and human flourishing. Individual freedom can only exist in the context of free-market capitalism. Personal freedom thrives in capitalism, declines in government-regulated economies, and vanishes in communism. Aside from better economic and legislative policies, what America needs is a more intense appreciation for individual',
    canonical: '/educational-articles/fee-stories/',
  }),
  title: {
    absolute:
      'FEE Stories – I Grew Up in a Communist System. Here’s What Americans Don’t Understand About Freedom - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13056 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/fee-stories') }}
    />
  )
}
