import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Games and Learning - New Heights Educational Group, Inc.',
    description:
      'Games and learning have always been considered as separate entities by traditional education system. Despite this fact, a large number of students and even adults spend millions of hours completely immersed in games sitting in front of TVs, computers, mobile phones, iPads or other PDAs. The demands and needs of the modern world have changed',
    canonical: '/educational-articles/games-and-learning/',
  }),
  title: { absolute: 'Games and Learning - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1503 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('educational-articles/games-and-learning'),
      }}
    />
  )
}
