import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Briana Dincher | NHEG Radio Show | New Heights Educational Group',
    description:
      'Briana Dincher is a high school student from New York City. She enjoys writing, poetry, reading crime novels, volunteering and playing badminton.',
    canonical: '/radio/briana-dincher/',
  }),
  title: { absolute: 'Briana Dincher | NHEG Radio Show | New Heights Educational Group' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-255 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/briana-dincher') }}
    />
  )
}
