// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Sarika Gauba, Author at New Heights Educational Group, Inc. | Page 2 of 3',
    description:
      'Sarika Gauba, page 2 of 3: Prom Cruise Celebration, Exciting news for the High School Symposium and College Fair, FEE Stories – Why College Degrees Are…',
    canonical: '/author/sarika-g/page/2/',
  }),
  title: { absolute: 'Sarika Gauba, Author at New Heights Educational Group, Inc. | Page 2 of 3' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-sarika-g author-945 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-2"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/sarika-g/page/2') }}
    />
  )
}
