import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Welcomes Radio Host Buffie Williams to the Airwaves - New Heights Educational Group, Inc.',
    description: 'The New Heights Educational Group (NHEG) welcomes Buffie Williams, who will host her first internet radio show on Tuesday, November 26 @ 6:00 p.m. CST/ 7:00 p.m. EST. On her show, Ms. Williams will connect the audience to education and how it powers the world, restructuring needed in public schools, the IEP process and bi-monthly',
    canonical: '/nheg-news/nheg-welcomes-radio-host-buffie-williams/',
  }),
  title: { absolute: 'NHEG Welcomes Radio Host Buffie Williams to the Airwaves - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8567 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-welcomes-radio-host-buffie-williams') }}
    />
  )
}
