import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Pre-Calculus - NHEG Online Learning Annex',
    description:
      'NHEG Precalculus is a pre-college level course typically taken by 12th graders. It contains reviews of algebra, geometry and functions, and it also adds…',
    canonical: '/school/online-courses/pre-calculus/',
  }),
  title: { absolute: 'Pre-Calculus - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-8422 page-child parent-pageid-2 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/online-courses/pre-calculus') }}
    />
  )
}
