import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Great Nonprofits Top-Rated Award 2016 - New Heights Educational Group, Inc.',
    description: 'New Heights Educational Group announced today that it has been honored with a prestigious Top-Rated Award by GreatNonprofits.org, the leading provider of user reviews about nonprofit organizations. This award is based on positive online reviews. “We are excited to be named a Top-Rated 2016 Nonprofit,” says Pamela Clark, Executive Director of the New Heights Educational',
    canonical: '/nheg-news/nheg-great-nonprofits-top-rated-award-2016/',
  }),
  title: { absolute: 'NHEG Great Nonprofits Top-Rated Award 2016 - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1820 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-great-nonprofits-top-rated-award-2016') }}
    />
  )
}
