import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Pokemon TCG - New Heights Educational Group, Inc.',
    description:
      'How can Pokemon TCG be educational for kids? Can adults play the game? What is the negative side of playing this game? This article will explain the basics of what the game is and how it can be an educational tool. What is Pokemon TCG? TCG is short for trading card game. The game became',
    canonical: '/education-news/pokemon-tcg/',
  }),
  title: { absolute: 'Pokemon TCG - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8335 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('education-news/pokemon-tcg') }}
    />
  )
}
