import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Men’s Ultra Cotton Tank Top - New Heights Educational Group, Inc.',
    description: 'S M L XL 2XL Width, in 17.99 20.00 22.01 24.02 25.98 Length, in 28.03 29.02 30.04 31.02 32.05 The men\'s ultra cotton tank top is just that - ultra. The fabric is 100% cotton for solids, while heather varieties include polyester. These fabrics all serve as excellent base laters for printing. All bindings',
    canonical: '/product/mens-ultra-cotton-tank-top-4/',
  }),
  title: { absolute: 'Men’s Ultra Cotton Tank Top - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-10622 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/mens-ultra-cotton-tank-top-4') }}
    />
  )
}
