import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: '2017 ServeOhio Award - New Heights Educational Group, Inc.',
    description:
      'Today is a great honor as New Heights Educational Group\'s Director, Pamela Clark has received the 2017 ServeOhio Award from the Ohio Governor John Kasich. Pamela received this wonderful award on the 14th of April. Below is the citation for the award: "On behalf of the State of Ohio, we congratulate you on being nominated for a',
    canonical: '/nheg-news/2017-serveohio-award/',
  }),
  title: { absolute: '2017 ServeOhio Award - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-5785 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/2017-serveohio-award') }}
    />
  )
}
