import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'School Bag Give Away - New Heights Educational Group, Inc.',
    description:
      'School Bag Give Away: Update on Our Recent School Bag Giveaway, 2nd Annual School Bag Giveaway After Party, Get Your School Bag Today – We Have 70+ Bags…',
    canonical: '/tag/school-bag-give-away/',
  }),
  title: { absolute: 'School Bag Give Away - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tag tag-school-bag-give-away tag-13 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tag/school-bag-give-away') }}
    />
  )
}
