import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Affiliates & Partners - New Heights Educational Group, Inc.',
    description:
      "NHEG couldn't provide the support and educational needs of the children and adults without the support of our many affiliates and partners across the country. We would like to take this opportunity to acknowledge and thank everyone for their support.",
    canonical: '/who-we-are/affiliates-partners/',
  }),
  title: { absolute: 'Affiliates & Partners - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-234 page-child parent-pageid-3409 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('who-we-are/affiliates-partners') }}
    />
  )
}
