import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Groups - NHEG Online Learning Annex',
    description: 'NHEG Support Groups provide various support to not only our board members but to students, parents and the teachers in Ohio. Each group provides a pivotal function in our organization to strengthen our programs and services plus help support and educate children and adults, so they can build a much stronger educational background.',
    canonical: '/school/about/nheg-groups/',
  }),
  title: { absolute: 'NHEG Groups - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-6458 page-parent page-child parent-pageid-358 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/about/nheg-groups') }}
    />
  )
}
