import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Classic Learning Test - NHEG Online Learning Annex',
    description: 'NHEG is happy to support and bring awareness to a new college entrance exam that focuses on classical learning; it\'s called the Classic Learning Test. We hope that it will replace the SAT and ACT exam for home-school, classical school or private Christian school families.',
    canonical: '/school/students/college-entrance-exams/classic-learning-test/',
  }),
  title: { absolute: 'Classic Learning Test - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-381 page-child parent-pageid-379 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/students/college-entrance-exams/classic-learning-test') }}
    />
  )
}
