import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'The Importance of Safety II – Human Trafficking - New Heights Educational Group, Inc.',
    description: 'Human trafficking is something that travelers should be aware when traveling. Human trafficking is a type of slavery in which one is forced into sexual acts or labor without his or her free will, as the kidnapper will use blackmail or force to make the victims obey. If you see someone in need of help,',
    canonical: '/educational-articles/the-importance-of-safety-ii-human-trafficking/',
  }),
  title: { absolute: 'The Importance of Safety II – Human Trafficking - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7982 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/the-importance-of-safety-ii-human-trafficking') }}
    />
  )
}
