import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Books - New Heights Educational Group, Inc.',
    description:
      'The NHEG Books catalog contains books published by members of our team that we are proud to support. We provide information on the books and where you can buy them.',
    canonical: '/who-we-are/nheg-books/',
  }),
  title: { absolute: 'Books - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-1757 page-parent page-child parent-pageid-3409 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('who-we-are/nheg-books') }}
    />
  )
}
