// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Shop | Page 5 of 8 | New Heights Educational Group, Inc.',
    description:
      '0 Cart This form has moved to email. We read every message. info@newheightseducation.org Shop Home » Shop ALL PRODUCTS This form has moved to email. We…',
    canonical: '/shop/page/5/',
  }),
  title: { absolute: 'Shop | Page 5 of 8 | New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive post-type-archive post-type-archive-product wp-theme-jupiter theme-jupiter woocommerce-shop woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-5"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('shop/page/5') }}
    />
  )
}
