import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'New Volunteer: Jeff Ermoian - New Heights Educational Group, Inc.',
    description:
      'Jeff Ermoian brings a passion for media and arts education to the NHEG team. Those passions are revealed in his career path. TV Producer, Corporate Trainer, Illustrator, Cartoonist, Animator, Author, Performer, Copywriter, Art Director and Pre-Press Network Administrator are among the titles held during his long career in visual communication. Jeff has 8 years of',
    canonical: '/nheg-news/new-volunteer-jeff-ermoian/',
  }),
  title: { absolute: 'New Volunteer: Jeff Ermoian - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-4782 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/new-volunteer-jeff-ermoian') }}
    />
  )
}
