import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Barbara Bullen - NHEG Radio Show',
    description: 'Barbara has a B.A. in Political Science with a Minor in Prelaw, a J.D. and LLM.',
    canonical: '/radio/barbara-bullen/',
  }),
  title: { absolute: 'Barbara Bullen - NHEG Radio Show' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-12643 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/barbara-bullen') }}
    />
  )
}
