// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Daniela Silva',
    description:
      'Daniela Silva, page 2 of 2: Developing the Potential in Children with Attention-Hyperactivity Disorder, Homeschooling: A New Perspective of Educating…',
    canonical: '/author/daniela-silva/page/2/',
  }),
  title: { absolute: 'Daniela Silva' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-daniela-silva author-5 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-2"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/daniela-silva/page/2') }}
    />
  )
}
