import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'New Heights Educational Group Publications – Inspire & Empower - NHEG',
    description: 'NHEG PUBLICATIONS This form has moved to email. We read every message. Info@NewHeightsEducation.org Sign up Sign up NHEG PUBLICATIONS Sign up Sign up…',
    canonical: '/',
  }),
  title: { absolute: 'New Heights Educational Group Publications – Inspire & Empower - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone home wp-singular page-template page-template-elementor_header_footer page page-id-6271 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-page-builder-template ast-no-sidebar astra-4.13.12 group-blog ast-single-post ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-template-full-width elementor-kit-5709 elementor-page elementor-page-6271"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('index') }}
    />
  )
}
