import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Student Support Services | New Heights Educational Group | Ohio',
    description:
      'The New Heights Educational Group promotes literacy for children and adults by offering a range of student support services for their educational needs.',
    canonical: '/',
  }),
  title: { absolute: 'Student Support Services | New Heights Educational Group | Ohio' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone home wp-singular page-template-default page page-id-3410 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('index') }}
    />
  )
}
