import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'New Partner Courses - New Heights Educational Group, Inc.',
    description:
      'Check out the brand new and free courses from Hillsdale College. Discounted & Free Online Classes - NHEG Online Learning Annex (newheightseducation.org)',
    canonical: '/community-news/new-partner-courses/',
  }),
  title: { absolute: 'New Partner Courses - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13378 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('community-news/new-partner-courses') }}
    />
  )
}
