import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Community News - New Heights Educational Group, Inc.',
    description: 'Our community news articles are written to help recognize our students, staff and other members of the community in their achievements. Of course, we wish to mention various events that are happening in the many communities in the state of Ohio.',
    canonical: '/category/community-news/',
  }),
  title: { absolute: 'Community News - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-community-news category-2 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/community-news') }}
    />
  )
}
