import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Conversations with Curt: NHEG 10th Anniversary Interview - New Heights Educational Group, Inc.',
    description: 'https://www.youtube.com/watch?v=ABzh8HGXXK0 Recently NHEG Director Pamela Clark and Maggie Spangler sat down with "Conversations with Curt" host Curt Aldrich and talked about NHEG\'s 10th Anniversary. In our half out interview with Curt, we talked about the beginnings of our organization, what goals our organization set, our programs and services that we provide to children and parents in',
    canonical: '/nheg-news/nhegs-10th-anniversary-interview/',
  }),
  title: { absolute: 'Conversations with Curt: NHEG 10th Anniversary Interview - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-2201 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nhegs-10th-anniversary-interview') }}
    />
  )
}
