import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Daniela Silva',
    description:
      'Daniela Silva: From the world of imagination: a day in the park with preschool students, Memories of a childhood rich in stimulus and its importance for…',
    canonical: '/author/daniela-silva/',
  }),
  title: { absolute: 'Daniela Silva' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-daniela-silva author-5 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/daniela-silva') }}
    />
  )
}
