import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'Grade Inflation Eats Away at the Meaning of College - New Heights Educational Group, Inc.',
    description:
      'The Year Was 2081 and Everyone Was Finally Above Average Thursday, April 21, 2016 Every so often, the issue of grade inflation makes the headlines, and we are reminded that grades are being debased continuously. That happened in late March when the two academics who have most assiduously studied grade inflation — Stuart Rojstaczer and Christopher Healy — provided fresh evidence',
    canonical: '/educational-articles/grade-inflation-eats-away-at-the-meaning-of-college/',
  }),
  title: {
    absolute:
      'Grade Inflation Eats Away at the Meaning of College - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13036 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'educational-articles/grade-inflation-eats-away-at-the-meaning-of-college'
        ),
      }}
    />
  )
}
