import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Looking for Library Space - New Heights Educational Group, Inc.',
    description: 'Do you have an empty building? The New Heights Educational Group is in urgent need of finding a new donated location for an educational library. Our library currently offers more than 3,803 books on different curriculum and encyclopedias. We also offer over 101 pieces of software and 139 DVD and VHS Tapes. We have a',
    canonical: '/nheg-news/looking-library-space/',
  }),
  title: { absolute: 'Looking for Library Space - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1823 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/looking-library-space') }}
    />
  )
}
