import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Manya Shukla – Host of Empowering HR within the Workforce - NHEG Radio Show',
    description:
      'Empowering HR within the Workforce is the podcast by Manya Shukla where we explore the latest trends in human resources, workforce development…',
    canonical: '/radio/manya-shukla/',
  }),
  title: {
    absolute: 'Manya Shukla – Host of Empowering HR within the Workforce - NHEG Radio Show',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-12921 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/manya-shukla') }}
    />
  )
}
