// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Khrista Cendana, Author at New Heights Educational Group, Inc. | Page 3 of 3',
    description:
      '0 Cart This form has moved to email. We read every message. info@newheightseducation.org Archives Author Archive for: "Khrista Cendana" Home » Archives for…',
    canonical: '/author/khrista-cendana/page/3/',
  }),
  title: {
    absolute: 'Khrista Cendana, Author at New Heights Educational Group, Inc. | Page 3 of 3',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-khrista-cendana author-4 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-3"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('author/khrista-cendana/page/3') }}
    />
  )
}
