import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Partnership with SVHS - New Heights Educational Group, Inc.',
    description: 'The New Heights Educational Group (NHEG) is furthering its partnership with Silicon Valley High School (SVHS). Silicon Valley High School (SVHS) is located in California and offers online learning courses to students of all ages. Its mission is to enhance the quality, relevance and accessibility of online high-school education while driving down the cost. These',
    canonical: '/nheg-news/partnership-with-svhs/',
  }),
  title: { absolute: 'Partnership with SVHS - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8595 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/partnership-with-svhs') }}
    />
  )
}
