import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'From the world of imagination: a day in the park with preschool students - New Heights Educational Group, Inc.',
    description: 'On a sunny morning a group of preschoolers went to the park with their teachers. Two students, Arthur and Peter, after playing a lot in the park with their toys, found a large cardboard box that was in the school\'s recyclables. Arthur looked at Peter and with bright eyes of joy exclaimed: "Peter, why don’t',
    canonical: '/educational-articles/from-the-world-of-imagination-a-day-in-the-park-with-preschool-students/',
  }),
  title: { absolute: 'From the world of imagination: a day in the park with preschool students - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8817 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/from-the-world-of-imagination-a-day-in-the-park-with-preschool-students') }}
    />
  )
}
