import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Sensory & Motor Skills in Children with Developmental Disorders - New Heights Educational Group, Inc.',
    description: 'According to the DSM-V (Diagnostic and Statistical Manual of Mental Disorders) developmental disorders are developmental conditions that usually arise before the child enters school and are characterized by deficits that result in impairment in personal, social, academic or professional functioning. Learning is a process that involves progressive changes in the individual\'s behavior, as a result',
    canonical: '/educational-articles/sensory-and-motor-skills-in-children-with-developmental-disorders/',
  }),
  title: { absolute: 'Sensory & Motor Skills in Children with Developmental Disorders - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8256 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/sensory-and-motor-skills-in-children-with-developmental-disorders') }}
    />
  )
}
