import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'College Entrance Exams - NHEG Online Learning Annex',
    description:
      'Many colleges and universities across the country use college entrance exams like the SATs to determine if they accept you into their school or not. These tests take on average three and a half hours, and so students and schools spend months preparing for these tests.',
    canonical: '/school/students/college-entrance-exams/',
  }),
  title: { absolute: 'College Entrance Exams - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-379 page-parent page-child parent-pageid-6467 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/students/college-entrance-exams'),
      }}
    />
  )
}
