import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG SAG Matte Onyx Bracelet - New Heights Educational Group, Inc.',
    description: 'One SizeBracelet Diameter , in2.17Coin Pendant Diameter, in0.67Tile Pendant Diameter, in0.67The onyx bracelet is expertly hand cast and polished in the USA and features vibrant, textured and glossy enamel-style coloring..: Sterling silver or 18K gold plated pendant.: Elastic wire.: Several charm shapes.: Nickel and lead free',
    canonical: '/product/nheg-sag-matte-onyx-bracelet/',
  }),
  title: { absolute: 'NHEG SAG Matte Onyx Bracelet - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11548 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/nheg-sag-matte-onyx-bracelet') }}
    />
  )
}
