// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NEWHEIGHTSEDUCATION, Author at NHEG - Page 4 of 12',
    description:
      'NEWHEIGHTSEDUCATION, page 4 of 12: NHEG EdGuide September- October 2018, NHEG EdGuide July – August 2018, NHEG EdGuide March-April 2018, NHEG EdGuide…',
    canonical: '/publications/author/newheightseducation/page/4/',
  }),
  title: { absolute: 'NEWHEIGHTSEDUCATION, Author at NHEG - Page 4 of 12' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-newheightseducation author-1 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-no-sidebar astra-4.14.0 group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709 paged paged-4"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('publications/author/newheightseducation/page/4'),
      }}
    />
  )
}
