import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'New Partnership with Foundation for Economic Education - New Heights Educational Group, Inc.',
    description:
      'The New Heights Educational Group has recently partnered with Foundation for Economic Education (FEE). FEE has been a leading non-profit organization in teaching the principles of a free society since its founding in 1946 by Leonard E. Read. Today, FEE focuses on bringing freedom as a life philosophy to young audiences while striving to bring',
    canonical: '/nheg-news/new-partnership-with-fee/',
  }),
  title: {
    absolute:
      'New Partnership with Foundation for Economic Education - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-2816 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/new-partnership-with-fee') }}
    />
  )
}
