import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'NHEG – LIVE PERFORMANCE – CIVIC THEATRE FOR THOSE IN FORT WAYNE AND NW OHIO AREA - New Heights Educational Group, Inc.',
    description:
      'Use code: NHEG - for free tickets, otherwise it costs $30 each Fort Wayne Civic Theatre | Ticket Search Options',
    canonical:
      '/nheg-news/nheg-live-performance-civic-theatre-for-those-in-fort-wayne-and-nw-ohio-area/',
  }),
  title: {
    absolute:
      'NHEG – LIVE PERFORMANCE – CIVIC THEATRE FOR THOSE IN FORT WAYNE AND NW OHIO AREA - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13003 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'nheg-news/nheg-live-performance-civic-theatre-for-those-in-fort-wayne-and-nw-ohio-area'
        ),
      }}
    />
  )
}
