import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG School Sale - New Heights Educational Group, Inc.',
    description:
      '0 Cart This form has moved to email. We read every message. Info@NewHeightsEducation.org NHEG School Sale Home » NHEG School Sale NHEG School Sale By…',
    canonical: '/nheg-news/nheg-school-sale/',
  }),
  title: { absolute: 'NHEG School Sale - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7631 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-school-sale') }}
    />
  )
}
