import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Edgar Allan Poe: The Midnight Collection - New Heights Educational Group, Inc.',
    description: 'The New Heights Educational Group (NHEG) has partnered with Chamber Theatre Productions in Quincy, MA, to offer Edgar Allan Poe: The Midnight Collection, an online one-hour dramatic educational experience featuring four of Poe’s works. Included in the collection are three live dramatizations of stories and poems, an audio poem, an animated biography of Poe’s life,',
    canonical: '/nheg-news/edgar-allan-poe-the-midnight-collection/',
  }),
  title: { absolute: 'Edgar Allan Poe: The Midnight Collection - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-9421 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/edgar-allan-poe-the-midnight-collection') }}
    />
  )
}
