import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Valentine’s Day - New Heights Educational Group, Inc.',
    description: 'What is Valentine’s Day, you might ask? One would assume that it is a day for love, where your husband, wife, girlfriend or boyfriend buy romantic gifts or plan a getaway vacation. But the holiday does not have to be about romance; not everyone has a romantic partner during Valentine’s Day. You can still give',
    canonical: '/educational-articles/valentines-day/',
  }),
  title: { absolute: 'Valentine’s Day - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-5401 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/valentines-day') }}
    />
  )
}
