import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Grants and Donations - New Heights Educational Group, Inc.',
    description:
      'We would like to thank everyone for the donations NHEG has received in order to support our educational programs and services that are used by students. We also like to thank the many organizations that have awarded grants to NHEG as well.',
    canonical: '/support-nheg/donations-nheg-has-received/',
  }),
  title: { absolute: 'Grants and Donations - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-2788 page-child parent-pageid-1897 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('support-nheg/donations-nheg-has-received'),
      }}
    />
  )
}
