import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Pamela’s Talk: NHEG - New Heights Educational Group, Inc.',
    description: 'https://youtu.be/ysNMMnT_wkQ Today\'s episode titled Pamela\'s Talk - NHEG, Pamela Clark discusses her passion, purpose, inspiration and advancements of the New Heights Educational Group.',
    canonical: '/pamelas-talk/pamelas-talk-nheg/',
  }),
  title: { absolute: 'Pamela’s Talk: NHEG - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-4498 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('pamelas-talk/pamelas-talk-nheg') }}
    />
  )
}
