// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NEWHEIGHTSEDUCATION, Author at NHEG - Page 10 of 12',
    description:
      'NHEG PUBLICATIONS This form has moved to email. We read every message. info@newheightseducation.org Sign up Sign up NHEG PUBLICATIONS Sign up Sign up…',
    canonical: '/publications/author/newheightseducation/page/10/',
  }),
  title: { absolute: 'NEWHEIGHTSEDUCATION, Author at NHEG - Page 10 of 12' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive author author-newheightseducation author-1 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-no-sidebar astra-4.14.0 group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709 paged paged-10"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('publications/author/newheightseducation/page/10'),
      }}
    />
  )
}
