// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Educational Articles - New Heights Educational Group, Inc. - Page 4',
    description:
      'Our educational articles archives consist of education based articles written by teachers, students and other members of the community.',
    canonical: '/category/educational-articles/page/4/',
  }),
  title: { absolute: 'Educational Articles - New Heights Educational Group, Inc. - Page 4' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-educational-articles category-3 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive paged paged-4"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/educational-articles/page/4') }}
    />
  )
}
