import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Assessment - NHEG Online Learning Annex',
    description:
      'This is an overview on how New Heights Educational Group works with students and their individual NHEG Assessments in order to track the students’ growth.',
    canonical: '/school/parents/nheg-assessment/',
  }),
  title: { absolute: 'NHEG Assessment - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-5822 page-child parent-pageid-420 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/parents/nheg-assessment') }}
    />
  )
}
