import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Premium Fleece Joggers - New Heights Educational Group, Inc.',
    description: 'S M L XL 2XL Waist, in 15.00 15.98 17.01 17.99 18.98 Inseam, in 28.98 30.00 30.98 31.97 32.99 Outseam, in 38.98 40.00 40.98 41.97 42.99 Staying active is no problem when you’ve got a stylish pair of premium-quality joggers like these. The back pocket is customizable and has two spacious pockets on the',
    canonical: '/product/premium-fleece-joggers/',
  }),
  title: { absolute: 'Premium Fleece Joggers - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-10668 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/premium-fleece-joggers') }}
    />
  )
}
