import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Unisex Heavy Blend™ Hooded Sweatshirt - New Heights Educational Group, Inc.',
    description: 'A unisex heavy blend hooded sweatshirt is relaxation itself. The material is a thick blend of cotton and polyester. This makes for a plush, soft feel alongside warmth. It\'s also a great surface for printing. There are no side seams. A spacious kangaroo pocket hangs in front. The hood\'s drawstring is the same color as',
    canonical: '/product/unisex-heavy-blend-hooded-sweatshirt/',
  }),
  title: { absolute: 'Unisex Heavy Blend™ Hooded Sweatshirt - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11221 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/unisex-heavy-blend-hooded-sweatshirt') }}
    />
  )
}
