import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Platinum Seal of Transparency 2024 - New Heights Educational Group, Inc.',
    description: 'We’ve earned our Platinum Seal of Transparency with @CandidDotOrg! Get updates on our impact through our #NonprofitProfile NEW HEIGHTS EDUCATIONAL GROUP - GuideStar Profile',
    canonical: '/community-news/13429/',
  }),
  title: { absolute: 'Platinum Seal of Transparency 2024 - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-13429 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('community-news/13429') }}
    />
  )
}
