import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Brochure - New Heights Educational Group, Inc.',
    description: 'We are happy to announce that New Heights Educational Group has released a new brochure so be on the look out for our brochure in the Defiance community. Of course, you can easily download and share our brochure with the following images. We like to thank our Graphics team, especially Kevin Adusei and Jeff Ermoian for',
    canonical: '/nheg-news/nheg-brochure/',
  }),
  title: { absolute: 'NHEG Brochure - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-6154 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-brochure') }}
    />
  )
}
