import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Globee Awards Wins Part 2 - New Heights Educational Group, Inc.',
    description: 'NHEG announced today that The Globee® Awards, organizers of world’s premier business awards programs and business ranking lists, has named NHEG, Executive Director Pamela Clark, and Team Members 7x winners in the prestigious awards. Check out the other Globee Awards we have won here. Executive Hero of the Year | Effective Leadership During COVID-19 Pamela',
    canonical: '/nheg-news/globee-awards-wins-part-2/',
  }),
  title: { absolute: 'Globee Awards Wins Part 2 - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-9931 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/globee-awards-wins-part-2') }}
    />
  )
}
