import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Weekender Bag - New Heights Educational Group, Inc.',
    description: '24x13Length, in24.02Width, in13Depth, in5.52Handle height, in11.42Our oversized Weekender Tote is perfect for your weekend at the beach or in town. The wide-mouthed, durable bag holds a generous amount of personal items and is easily held by its thick rope handles..: 100% Spun Polyester.: T-bottom.: Laminated lining',
    canonical: '/product/weekender-bag/',
  }),
  title: { absolute: 'Weekender Bag - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11589 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/weekender-bag') }}
    />
  )
}
