import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG EDGuide-May-June 2023 - NHEG',
    description:
      'Read the latest in education in the May-June 2023 issue of EdGuide magazine by the New Heights Educational Group.',
    canonical: '/publications/books/nheg-edguide-may-june-2023/',
  }),
  title: { absolute: 'NHEG EDGuide-May-June 2023 - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular dflip-template-default single single-dflip postid-5894 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-right-sidebar astra-4.13.12 ast-sticky-sidebar group-blog ast-blog-single-style-1 ast-custom-post-type ast-single-post ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header ast-normal-title-enabled elementor-default elementor-kit-5709"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('publications/books/nheg-edguide-may-june-2023'),
      }}
    />
  )
}
