import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG SAG Backpack (Made in USA) - New Heights Educational Group, Inc.',
    description: 'One SizeLength, in11.82Width, in5.12Height , in18.12Have you got room for all that? With our roomy and durable backpack, you will! This bag is made from spun polyester and weights 1.3 lbs, just enough to be light, strong and long lasting. Grab it, stow it, throw it onto the seat next to you, this backpack can',
    canonical: '/product/nheg-sag-backpack-made-in-usa/',
  }),
  title: { absolute: 'NHEG SAG Backpack (Made in USA) - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11648 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/nheg-sag-backpack-made-in-usa') }}
    />
  )
}
