import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Volunteer - New Heights Educational Group, Inc.',
    description: 'Volunteer with NHEG, and you will help bring education and learning opportunities to thousands of children and adults in the state of Ohio. Our volunteers work hard and are from all over the world.',
    canonical: '/volunteer-with-nheg/',
  }),
  title: { absolute: 'Volunteer - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-576 page-parent wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('volunteer-with-nheg') }}
    />
  )
}
