import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Nelson Medela - New Heights Educational Group, Inc.',
    description:
      'Written by: Barbara Bullen Nelson Rolihlahla Mandela known throughout the world as a revolutionary and political leader who aided in the dismantling of Apartheid; Black South Africans whose lives were filled with fear due to the historical racist and prejudicial governmental policies of South Africa found their hero in Mandela. The world craved such a',
    canonical: '/educational-articles/nelson-medela/',
  }),
  title: { absolute: 'Nelson Medela - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-12721 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/nelson-medela') }}
    />
  )
}
