import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Teacher Portal - NHEG Online Learning Annex',
    description: 'The NHEG Teachers Portal is a dedicated page of information, resources, organizations and professional development for teachers in Ohio.',
    canonical: '/school/teachers/',
  }),
  title: { absolute: 'Teacher Portal - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-260 page-parent wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/teachers') }}
    />
  )
}
