import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Students - NHEG Online Learning Annex',
    description: 'The NHEG Student Portal contains information and links for students who are homeschooled, attending charter schools or public schools in Ohio. This includes students who are in Pre-K, K-12 or attending college.',
    canonical: '/school/students/',
  }),
  title: { absolute: 'Students - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-6467 page-parent wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/students') }}
    />
  )
}
