// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Community News - New Heights Educational Group, Inc. - Page 3',
    description:
      'Our community news articles are written to help recognize our students, staff and other members of the community in their achievements. Of course, we wish to mention various events that are happening in the many communities in the state of Ohio. - Page 3',
    canonical: '/category/community-news/page/3/',
  }),
  title: { absolute: 'Community News - New Heights Educational Group, Inc. - Page 3' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-community-news category-2 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive paged paged-3"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/community-news/page/3') }}
    />
  )
}
