import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Awards - New Heights Educational Group, Inc.',
    description:
      'Over the years of dedicated service to the children and adults of the state of Ohio, we have received many awards and achievements for the work that we do. These awards and achievements cover various areas, including businesses and education. Each award and achievement is listed by name, the year we received it and, if appropriate, the category for which we were nominated.',
    canonical: '/who-we-are/awards-and-achievements/',
  }),
  title: { absolute: 'Awards - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-57 page-parent page-child parent-pageid-3409 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('who-we-are/awards-and-achievements') }}
    />
  )
}
