import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Discounted & Free Online Classes - NHEG Online Learning Annex',
    description:
      'NHEG is providing students discounted and free online classes that they can take in their free time or incorporate into their current studies. This…',
    canonical: '/school/online-courses/discounted-and-free-online-classes/',
  }),
  title: { absolute: 'Discounted & Free Online Classes - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-360 page-child parent-pageid-2 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/online-courses/discounted-and-free-online-classes'),
      }}
    />
  )
}
