// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG EDGuide Archives - Page 3 of 7 - NHEG',
    description:
      'NHEG EDGuide Archives, page 3 of 7: NHEG EdGuide February 2016, NHEG EdGuide January 2016, NHEG EdGuide November- December 2017, NHEG EdGuide…',
    canonical: '/publications/category/nheg-edguide/page/3/',
  }),
  title: { absolute: 'NHEG EDGuide Archives - Page 3 of 7 - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-nheg-edguide category-22 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-no-sidebar astra-4.14.0 group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709 paged paged-3"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('publications/category/nheg-edguide/page/3'),
      }}
    />
  )
}
