import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Footer area - New Heights Educational Group, Inc.',
    description:
      '0 Cart This form has moved to email. We read every message. info@newheightseducation.org | Home | Learning Annex | Programs | Support | Volunteer | Events…',
    canonical: '/footer-area/',
  }),
  title: { absolute: 'Footer area - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-7370 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('footer-area') }}
    />
  )
}
