import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Holiday Giving from NHEG - New Heights Educational Group, Inc.',
    description: 'Over fifty toys were distributed to the NW Ohio families for Christmas thanks to a collaboration between the New Heights Educational Group (NHEG) and two anonymous community sponsors. NHEG director Pamela Clark created a Facebook page seeking out families that needed food and gifts for Christmas. Pamela Clark stated, “This is the first time we',
    canonical: '/nheg-news/holiday-giving-from-nheg/',
  }),
  title: { absolute: 'Holiday Giving from NHEG - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8703 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/holiday-giving-from-nheg') }}
    />
  )
}
