import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Charlotte D. McGuire | NHEG Radio Show | NHEG',
    description:
      'Charlotte is currently a Coach for the Reclaiming Futures National Program Office and Servant-leader at Joshua Christian Ministries.',
    canonical: '/radio/charlotte-d-mcguire/',
  }),
  title: { absolute: 'Charlotte D. McGuire | NHEG Radio Show | NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-257 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/charlotte-d-mcguire') }}
    />
  )
}
