import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NSHSS Recognition - New Heights Educational Group, Inc.',
    description:
      "Pamela Clark, a recognized NSHSS Educator at New Heights Educational Group Resource and Literacy Center, is honored to share this opportunity with students to earn placement in the National Society of High School Scholars. Mrs. Clark has been nominating students since 2011, and all of the students she's nominated have been inducted into NSHSS. The",
    canonical: '/nheg-news/nshss-recognition/',
  }),
  title: { absolute: 'NSHSS Recognition - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7940 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nshss-recognition') }}
    />
  )
}
