// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Shop | Page 8 of 8 | New Heights Educational Group, Inc.',
    description:
      'Shop, page 8 of 8: Women’s Cut & Sew Racerback Dress, Women’s Ideal Racerback Tank.',
    canonical: '/shop/page/8/',
  }),
  title: { absolute: 'Shop | Page 8 of 8 | New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive post-type-archive post-type-archive-product wp-theme-jupiter theme-jupiter woocommerce-shop woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-8"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('shop/page/8') }}
    />
  )
}
