import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Recommended Books for Education - NHEG Online Learning Annex',
    description:
      'New Heights Educational Group has created a list of Recommended Books for Education that we use to help tutor students who come through our doors. These…',
    canonical: '/school/recommended-books-for-education/',
  }),
  title: { absolute: 'Recommended Books for Education - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-7166 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/recommended-books-for-education'),
      }}
    />
  )
}
