import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Home - NHEG',
    description:
      'A comprehensive guide to current educational topics, stories and news, along with highlights of the accomplishments, activities and achievements of the…',
    canonical: '/publications/home-4/',
  }),
  title: { absolute: 'Home - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template page-template-elementor_header_footer page page-id-8 wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-page-builder-template ast-no-sidebar astra-4.14.0 group-blog ast-single-post ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-theme-transparent-header ast-hfb-header ast-full-width-primary-header elementor-default elementor-template-full-width elementor-kit-5709"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('publications/home-4') }}
    />
  )
}
