import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Martin Luther King Jr. Day - New Heights Educational Group, Inc.',
    description: 'Written by: Barbara Bullen​ Martin Luther King Jr., (Michael King Jr., 1929-1968) known internationally throughout the world as one of the greatest mediators of all time, is honored yearly. Brought up as a Christian, he followed in his father’s footsteps (Martin Luther King, Sr.) by becoming a Baptist Minister. A man who took it upon',
    canonical: '/educational-articles/martin-luther-king-jr-day/',
  }),
  title: { absolute: 'Martin Luther King Jr. Day - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-10278 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('educational-articles/martin-luther-king-jr-day') }}
    />
  )
}
