import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Shop | New Heights Educational Group, Inc.',
    description:
      'Shop: AAG Duffel Bag, AAG Unisex Hooded Zip Sweatshirt, AAG Unisex Jersey Short Sleeve Tee, Baton Corps Unisex Jersey Short Sleeve Tee, Color Guard…',
    canonical: '/shop/',
  }),
  title: { absolute: 'Shop | New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive post-type-archive post-type-archive-product wp-theme-jupiter theme-jupiter woocommerce-shop woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('shop') }}
    />
  )
}
