// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Leadership Groups - New Heights Educational Group, Inc. - Page 4',
    description:
      'Adult and Student Leadership Collections Please allow three – four weeks to receive your order. - Page 4',
    canonical: '/product-category/leadership-groups/page/4/',
  }),
  title: { absolute: 'NHEG Leadership Groups - New Heights Educational Group, Inc. - Page 4' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tax-product_cat term-leadership-groups term-47 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive paged paged-4"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('product-category/leadership-groups/page/4'),
      }}
    />
  )
}
