// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Radio - New Heights Educational Group, Inc. - Page 2',
    description:
      'New Heights Show on Education Collections Please allow three – four weeks to receive your order.',
    canonical: '/product-category/nheg-radio/page/2/',
  }),
  title: { absolute: 'NHEG Radio - New Heights Educational Group, Inc. - Page 2' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive tax-product_cat term-nheg-radio term-46 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive paged paged-2"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product-category/nheg-radio/page/2') }}
    />
  )
}
