import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Victoria Lowery | NHEG Radio Show | New Heights Educational Group',
    description: 'Victoria Marie Lowery was born to Elmer and Sandi Deitering in Dayton, Ohio.',
    canonical: '/radio/victoria-lowery/',
  }),
  title: { absolute: 'Victoria Lowery | NHEG Radio Show | New Heights Educational Group' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-127 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/victoria-lowery') }}
    />
  )
}
