import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Online Piano Course - NHEG Online Learning Annex',
    description:
      'The Introduction to Piano course will help you get started on your musical path to learning piano. This brief course will provide you with all the basics…',
    canonical: '/school/online-courses/music-program/online-piano-course/',
  }),
  title: { absolute: 'Online Piano Course - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-7961 page-child parent-pageid-7907 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('school/online-courses/music-program/online-piano-course'),
      }}
    />
  )
}
