import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Recognition Day 2019 - New Heights Educational Group, Inc.',
    description: 'The New Heights Educational Group’s (NHEG) Recognition Day is a special event in which we recognize all the hard work that has been accomplished throughout the year. This includes our NHEG volunteers, teachers/tutors, our partners & sponsors and more importantly the students and their academic accomplishments. It also provides students an opportunity to share talents',
    canonical: '/nheg-news/nheg-recognition-day-2019/',
  }),
  title: { absolute: 'NHEG Recognition Day 2019 - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-8188 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-recognition-day-2019') }}
    />
  )
}
