import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Online Learning Annex',
    description:
      'The NHEG Learning Annex provides free and paid online courses for both children and adults looking to increase their educational and life skills. Our own NHEG teachers and tutors help develop these online courses for those looking for an easy-to-use online solution for their educational needs. Also, the NHEG Learning Annex partners with many educators across the country who provide online courses for both children and adults who are interested in learning new topics and skills.',
    canonical: '/school/',
  }),
  title: { absolute: 'NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone home wp-singular page-template-default page page-id-242 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school') }}
    />
  )
}
