import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Student Corner - New Heights Educational Group, Inc.',
    description: 'The NHEG Student Corner are articles written by students looking to not only give back to NHEG but increase their education through writing.',
    canonical: '/category/student-corner/',
  }),
  title: { absolute: 'Student Corner - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-student-corner category-16 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/student-corner') }}
    />
  )
}
