import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Privacy Policy - New Heights Educational Group, Inc.',
    description:
      'New Heights Educational Group, INC is an Ohio based organization with its home office at 14735 Power Dam Road. Since this is a home office, only scheduled appointments are allowed. New Heights Educational Group, INC (NHEG)is the owner and operator of www.NewHeightsEducation.org and School.NewHeightsEducation.org websites. NHEG is committed to protecting the in-person and online privacy of visitors to our websites.',
    canonical: '/privacy-policy/',
  }),
  title: { absolute: 'Privacy Policy - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone privacy-policy wp-singular page-template-default page page-id-208 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('privacy-policy') }}
    />
  )
}
