import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Launches New History on Civil Rights Show - New Heights Educational Group, Inc.',
    description:
      'NHEG is happy to welcome Barbara Bullen and her show on the history of civil rights to our lineup of radio shows. The New Heights Show on Education is going into its eighth year, and within that time, the award-winning show has garnered over 330,000 listeners. The show was syndicated in 2019 thanks to the',
    canonical: '/nheg-radio-show/nheg-launches-new-history-on-civil-rights-show/',
  }),
  title: {
    absolute:
      'NHEG Launches New History on Civil Rights Show - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-10319 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('nheg-radio-show/nheg-launches-new-history-on-civil-rights-show'),
      }}
    />
  )
}
