import React from 'react'
import { render, act } from '@testing-library/react'
import CloneEnhance from '@/components/clone-enhance'

/**
 * Two mobile-menu toggles, one panel.
 *
 * `wireMkMenu` runs once per `.mk-nav-responsive-link`, and each call resolves
 * the panel through `toggle.closest('header')` — so two controls in the same
 * header share one panel. It used to hold open/closed in a per-toggle boolean,
 * which made the second control believe the menu was shut after the first had
 * opened it: tapping it wrote `display: block` over an already-open panel, so
 * the panel did not close and the tap did nothing. That is the dead-control
 * shape this component exists to remove, reintroduced by the fix for it, and
 * `aria-expanded` on the untouched toggle was wrong for as long as it lasted.
 *
 * Not reachable on newheightseducation.org's current capture — measured across
 * all 793 built pages, every one carries exactly ONE toggle element (the second
 * string match per page is the escaped copy inside Next's hydration payload).
 * It is guarded here because `clone-enhance` is generated by workflow 706 into
 * every FFC-EX repo, and a Jupiter theme that renders one toggle per breakpoint
 * is an ordinary thing for the next capture to bring.
 *
 * The panel's inline `display: none` stands in for the theme's own stylesheet
 * rule (`.mk-responsive-wrap { display: none }`), which jsdom does not load.
 */
function buildHeader() {
  document.body.innerHTML = `
    <header>
      <div class="mk-nav-responsive-link" id="toggle-a"></div>
      <div class="mk-nav-responsive-link" id="toggle-b"></div>
      <div class="mk-responsive-wrap" style="display: none">
        <ul><li><a href="/who-we-are/">Who We Are</a></li></ul>
      </div>
    </header>`
  return {
    a: document.getElementById('toggle-a') as HTMLElement,
    b: document.getElementById('toggle-b') as HTMLElement,
    panel: document.querySelector('.mk-responsive-wrap') as HTMLElement,
  }
}

const expanded = (el: HTMLElement) => el.getAttribute('aria-expanded')

describe('wireMkMenu with two toggles on one panel', () => {
  it('lets either control close a panel the other opened', () => {
    const { a, b, panel } = buildHeader()
    render(<CloneEnhance />)

    expect(panel.style.display).toBe('none')

    act(() => {
      a.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    })
    expect(panel.style.display).toBe('block')

    // The second control must CLOSE it. With per-toggle state this wrote
    // `block` again and the panel stayed open.
    act(() => {
      b.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    })
    expect(panel.style.display).toBe('none')
  })

  it('keeps aria-expanded truthful on the control that was not tapped', () => {
    const { a, b, panel } = buildHeader()
    render(<CloneEnhance />)

    expect(expanded(a)).toBe('false')
    expect(expanded(b)).toBe('false')

    act(() => {
      a.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    })
    expect(panel.style.display).toBe('block')
    // Both describe the same panel, so both must say it is open.
    expect(expanded(a)).toBe('true')
    expect(expanded(b)).toBe('true')

    act(() => {
      b.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    })
    expect(expanded(a)).toBe('false')
    expect(expanded(b)).toBe('false')
  })

  /**
   * jsdom lays nothing out, so every element reports zero size and the
   * component's "which control is on screen?" test can only be exercised by
   * standing in for the layout. `getClientRects` is the branch that decides it,
   * so stubbing it on one toggle is the smallest honest stand-in for a
   * breakpoint where that control is the visible one.
   */
  function renderOnly(el: HTMLElement) {
    Object.defineProperty(el, 'getClientRects', {
      configurable: true,
      value: () => [{ width: 38, height: 38 }] as unknown as DOMRectList,
    })
  }

  it('returns focus to the control that is on screen, not the one wired first', () => {
    const { a, b, panel } = buildHeader()
    // At this width the theme renders the SECOND control. `a` stays hidden, and
    // `focus()` on a hidden element does nothing at all.
    renderOnly(b)
    render(<CloneEnhance />)

    act(() => {
      b.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    })
    expect(panel.style.display).toBe('block')

    act(() => {
      document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))
    })
    expect(panel.style.display).toBe('none')
    // Wiring order put `a` first, so a handler that focuses its own toggle
    // lands here instead -- closing the menu and stranding the visitor.
    expect(document.activeElement).toBe(b)
  })

  it('still announces both controls as buttons', () => {
    const { a, b } = buildHeader()
    render(<CloneEnhance />)

    for (const el of [a, b]) {
      expect(el.getAttribute('role')).toBe('button')
      expect(el.getAttribute('tabindex')).toBe('0')
      expect(el.getAttribute('aria-label')).toBe('Toggle menu')
    }
  })
})
