import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Japanese Live Classes will Start July 9th - New Heights Educational Group, Inc.',
    description:
      "The live Japanese classes will be held twice a week starting on July 9th. With classes being held on Mondays (7 pm-8 pm) and Thursdays (7 pm-8 pm). If you haven't registered yet for our class please do so today as seats are filling up. You can register by clicking here.",
    canonical: '/course-announcements/japanese-live-classes-will-start-july-9th/',
  }),
  title: {
    absolute: 'Japanese Live Classes will Start July 9th - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7605 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('course-announcements/japanese-live-classes-will-start-july-9th'),
      }}
    />
  )
}
