import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Show Latte mug - New Heights Educational Group, Inc.',
    description:
      '12ozHeight, in4.02Diameter , in3.71A true coffee lover knows that each variety of this aromatic drink deserves a special cup. This durable ceramic latte mug with high quality sublimation printing makes it a gift appreciated by any latte drinker..: White ceramic.: 12 oz (0.35l).: Rounded corners.: C-Handle',
    canonical: '/product/show-latte-mug/',
  }),
  title: { absolute: 'Show Latte mug - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11542 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/show-latte-mug') }}
    />
  )
}
