import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Partnership with CARS - New Heights Educational Group, Inc.',
    description: 'The New Heights Educational Group (NHEG) has been an active partner of IAA’s Donate A Car program for a number of years. IAA recently announced a merger with the Charitable Auto Resources (CARS) vehicle donation program. The IAA relationship will be active through May 12, 2021, and then NHEG will transition to the CARS program. CARS is',
    canonical: '/nheg-news/partnership-with-cars/',
  }),
  title: { absolute: 'Partnership with CARS - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-9797 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/partnership-with-cars') }}
    />
  )
}
