import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Sponsorship Radio & Magazine Ads - New Heights Educational Group, Inc.',
    description: 'New Heights Educational Group is proud to announce our NHEG Sponsorship Ads for both our radio programs and monthly magazine. By sponsoring our radio show and magazine, your business or organization will not only help our organization build solid educational programs for students to participate but you also provide more educational opportunities in the state',
    canonical: '/nheg-news/nheg-sponsorship-ads/',
  }),
  title: { absolute: 'NHEG Sponsorship Radio & Magazine Ads - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-6094 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/nheg-sponsorship-ads') }}
    />
  )
}
