import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Health Is Your Wealth Book Review - New Heights Educational Group, Inc.',
    description: 'NHEG\'s latest book, Unraveling Reading has been reviewed by Health is Your Wealth Magazine. A British publication for readers with a neurological condition. Written by Daniela Silva, "Unraveling Reading is a response to the needs and difficulties faced by parents, students and teachers with respect to literacy and education. It presents strategies and alternatives for developing reading',
    canonical: '/nheg-news/health-is-your-wealth-magazine-book-review/',
  }),
  title: { absolute: 'Health Is Your Wealth Book Review - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-4716 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/health-is-your-wealth-magazine-book-review') }}
    />
  )
}
