import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Pre-Calculus - NHEG Online Learning Annex',
    description:
      'Pre-Calculus is an online course with recorded lectures that will help you strengthen your mathematic and, more specifically, calculus skills.',
    canonical: '/school/pre-calculus/',
  }),
  title: { absolute: 'Pre-Calculus - NHEG Online Learning Annex' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-8745 wp-theme-jupiter wpb-js-composer js-comp-ver-7.7.2 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('school/pre-calculus') }}
    />
  )
}
