import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title:
      'New Heights Educational Group Named Gold Globee® Winner - New Heights Educational Group, Inc.',
    description:
      'NHEG announced today that the Globee® Awards, organizers of world’s premier business awards programs and business ranking lists, has named New Heights Educational Group a Gold Globee® winner in the 11th Annual 2021 Communications Excellence Awards for its radio program and podcast “New Heights Show on Education,” and its educational magazine “New Heights Educational Group',
    canonical: '/nheg-news/new-heights-educational-group-named-gold-globee-winner/',
  }),
  title: {
    absolute:
      'New Heights Educational Group Named Gold Globee® Winner - New Heights Educational Group, Inc.',
  },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-10103 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent(
          'nheg-news/new-heights-educational-group-named-gold-globee-winner'
        ),
      }}
    />
  )
}
