import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Kathy Woodring | NHEG Radio Show | New Heights Educational Group',
    description:
      'Kathy’s show covers the history of the United States, from the early settlements to present day, focusing on significant events.',
    canonical: '/radio/kathy-woodring/',
  }),
  title: { absolute: 'Kathy Woodring | NHEG Radio Show | New Heights Educational Group' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-253 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/kathy-woodring') }}
    />
  )
}
