import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'dFlip Book Archive - NHEG',
    description:
      'NHEG PUBLICATIONS This form has moved to email. We read every message. Info@NewHeightsEducation.org Sign up Sign up NHEG PUBLICATIONS Sign up Sign up dFlip…',
    canonical: '/publications/books/',
  }),
  title: { absolute: 'dFlip Book Archive - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive post-type-archive post-type-archive-dflip wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-right-sidebar astra-4.13.12 ast-sticky-sidebar group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('publications/books') }}
    />
  )
}
