import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG Radio Show - New Heights Educational Group, Inc.',
    description:
      '0 Cart This form has moved to email. We read every message. Info@NewHeightsEducation.org NHEG Radio Show Home » NHEG Radio Show 0 By Michael Anderson In…',
    canonical: '/category/nheg-radio-show/',
  }),
  title: { absolute: 'NHEG Radio Show - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-nheg-radio-show category-11 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/nheg-radio-show') }}
    />
  )
}
