import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'NHEG SAG Box Chain Bracelet - New Heights Educational Group, Inc.',
    description:
      'One SizeWrist diameter (max), in3.15Chain diameter, in0.0393Ash-coin pendant diameter, in0.63Jaylon pendant length, in1.38Jaylon pendant width , in0.4This box chain bracelet emphasizes the delicate, vibrant and sensual personality of its wearer. Made in USA. .: Sterling silver or 18K gold plated.: Several charm shapes.: Slider for adjustable width.: Nickel and lead free',
    canonical: '/product/nheg-sag-box-chain-bracelet/',
  }),
  title: { absolute: 'NHEG SAG Box Chain Bracelet - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular product-template-default single single-product postid-11571 wp-theme-jupiter theme-jupiter woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('product/nheg-sag-box-chain-bracelet') }}
    />
  )
}
