import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: '2nd Annual School Bag Giveaway - New Heights Educational Group, Inc.',
    description:
      'https://youtu.be/dB34_tqvgU4 Dear families of school age children, The New Heights Educational Group (NHEG) is now accepting RSVP’s for the school bag giveaway. Thanks to First Federal Bank we have over 70 bags this year! “This surpassed our goal and last year’s collection by 27 bags!” The event will be held on July 28th from 3:30',
    canonical: '/nheg-news/2nd-annual-school-bag-giveaway/',
  }),
  title: { absolute: '2nd Annual School Bag Giveaway - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-7460 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('nheg-news/2nd-annual-school-bag-giveaway'),
      }}
    />
  )
}
