// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Shop | Page 6 of 8 | New Heights Educational Group, Inc.',
    description:
      'Shop, page 6 of 8: SAG Unisex Heavy Cotton Tee, SAG Unisex Hooded Zip Sweatshirt, SAG Unisex Jersey Short Sleeve Tee, Show Latte mug, Show Mug 11oz, Show…',
    canonical: '/shop/page/6/',
  }),
  title: { absolute: 'Shop | Page 6 of 8 | New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive post-type-archive post-type-archive-product wp-theme-jupiter theme-jupiter woocommerce-shop woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-6"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('shop/page/6') }}
    />
  )
}
