import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Travel Program - New Heights Educational Group, Inc.',
    description:
      "NHEG travel programs offers students and teachers the opportunity to experience, travel and understand new cultures around the world for the first time. Also, if you're a home school parent, NHEG offers the home school Family to Family Program.",
    canonical: '/nheg-educational-programs/nheg-travel/',
  }),
  title: { absolute: 'Travel Program - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-528 page-child parent-pageid-519 wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{
        __html: loadCloneContent('nheg-educational-programs/nheg-travel'),
      }}
    />
  )
}
