import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Footer - NHEG Radio Show',
    description:
      'Educational support services. Such services include the following: assisting families in the selection of schools; organization of educational…',
    canonical: '/radio/footer/',
  }),
  title: { absolute: 'Footer - NHEG Radio Show' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-243 wp-custom-logo wp-theme-jupiter wpb-js-composer js-comp-ver-8.7.2.1 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('radio/footer') }}
    />
  )
}
