import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: '12th Annual Golden Bridge Business and Innovation Awards - New Heights Educational Group, Inc.',
    description: 'New Heights Educational Group announced today that Golden Bridge Awards has named Tyler Maxey-Billings, Marina Klimi and Michael Anderson as Silver winners in the 12th Annual 2020 Golden Bridge Business and Innovation Awards. The coveted annual Golden Bridge Awards program recognizes and honors the world’s best in organizational performance, products and services, innovations, executives and',
    canonical: '/nheg-news/12th-annual-golden-bridge-business-and-innovation-awards/',
  }),
  title: { absolute: '12th Annual Golden Bridge Business and Innovation Awards - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-9289 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/12th-annual-golden-bridge-business-and-innovation-awards') }}
    />
  )
}
