// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'dFlip Book Archive - Page 8 of 9 - NHEG',
    description:
      'dFlip Book Archive, page 8 of 9: NHEG EDGuide-March-April-2023, NHEG EDGuide-May-June 2023, NHEG EDGuide July-August-2023, NHEG EDGuide September-October…',
    canonical: '/publications/books/page/8/',
  }),
  title: { absolute: 'dFlip Book Archive - Page 8 of 9 - NHEG' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive post-type-archive post-type-archive-dflip wp-custom-logo wp-embed-responsive wp-theme-astra ast-desktop ast-separate-container ast-two-container ast-right-sidebar astra-4.14.0 ast-sticky-sidebar group-blog ast-replace-site-logo-transparent ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-5709 paged paged-8"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('publications/books/page/8') }}
    />
  )
}
