// Generated by scripts/paginate-archives.mjs from the live archive (#41).
import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Shop | Page 4 of 8 | New Heights Educational Group, Inc.',
    description:
      'Shop, page 4 of 8: NHEG SAG Box Chain Bracelet, NHEG SAG Custom Pin Buttons, NHEG SAG Matte Onyx Bracelet, NHEG SAG Metal Pin, NHEG SLC AND NHEG SAG…',
    canonical: '/shop/page/4/',
  }),
  title: { absolute: 'Shop | Page 4 of 8 | New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive post-type-archive post-type-archive-product wp-theme-jupiter theme-jupiter woocommerce-shop woocommerce woocommerce-page woocommerce-no-js wpb-js-composer js-comp-ver-8.7.4 vc_responsive paged paged-4"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('shop/page/4') }}
    />
  )
}
