import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/page-metadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'School Supplies at ProMedica Defiance Regional Hospital - New Heights Educational Group, Inc.',
    description: 'Attention Families with School-age children. FOUR GREAT OPPORTUNITIES AT ONE SPECIAL EVENT - FREE SCHOOL SUPPLIES, HEALTH AND WELLNESS PRESENTATION, FREE DINNER, FREE READING TIME, WITH BOOKS TO BE HANDED OUT UPDATE - We would like to thank Kroger for contributing $100 gift card to purchase school supplies. UPDATE - Due to some extra donations',
    canonical: '/nheg-news/school-supplies/',
  }),
  title: { absolute: 'School Supplies at ProMedica Defiance Regional Hospital - New Heights Educational Group, Inc.' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-6082 single-format-standard wp-theme-jupiter theme-jupiter woocommerce-no-js wpb-js-composer js-comp-ver-8.7.3 vc_responsive"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('nheg-news/school-supplies') }}
    />
  )
}
